Public Enum ReportesWAP
    LISTADO_DE_REGISTRO_DE_EVENTOS_WAP = 0
    DIFERENCIAS_DE_TIEMPO_ENTRE_EVENTOS_WAP_POR_TRACTO = 1
    DIFERENCIAS_DE_TIEMPO_ENTRE_EVENTOS_WAP_POR_USUARIO = 100 'opcion removida del combo 
    LISTADO_DE_REGISTRO_DE_GPS_POR_VEHICULO = 2
    FLUJO_DE_ACTIVIDADES_POR_TRACTO = 3
    FLUJO_DE_ACTIVIDADES_POR_USUARIO = 101 'opcion removida del combo 
End Enum