DROP PROCEDURE SP_SOLMIN_SA_LISTAR_APLICACION_X_USUARIO
GO

CREATE PROCEDURE SP_SOLMIN_SA_LISTAR_APLICACION_X_USUARIO (
  IN IN_MMCUSR VARCHAR(10),
  IN IN_MMCAPL VARCHAR(2) )
  RESULT SETS 1
  LANGUAGE SQL
  BEGIN

  DECLARE CR CURSOR FOR

  SELECT DISTINCT MMAPLC.MMCAPL, MMAPLC.MMDAPL
    FROM MMAPLC, MMMENU, MMOPCN, MMOPUS, MMUSER
   WHERE MMAPLC.MMCAPL = MMMENU.MMCAPL
    AND MMMENU.MMCAPL = MMOPCN.MMCAPL
    AND MMMENU.MMCMNU = MMOPCN.MMCMNU
    AND MMOPCN.MMCAPL = MMOPUS.MMCAPL
    AND MMOPCN.MMCMNU = MMOPUS.MMCMNU
    AND MMOPCN.MMCOPC = MMOPUS.MMCOPC
    AND MMOPUS.MMCUSR = MMUSER.MMCUSR
    AND MMMENU.MMCAPL IN ( SELECT DISTINCT OPCN1.MMCAPL
                             FROM MMOPCN OPCN1
                            WHERE OPCN1.MMCAIN = IN_MMCAPL
                              AND OPCN1.MMCAPL <> IN_MMCAPL)
    AND MMMENU.SESTRG <> '*'
    AND MMUSER.MMCUSR = IN_MMCUSR ;

OPEN CR ;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_LISTAR_APLICACION_X_USUARIO TO PUBLIC

