-- BUSCA SI EXISTE SUBITEMS EN LA TABLA RZOL39S
DROP FUNCTION FN_SOLMIN_OC_SUBITEM_RZOL39S_CANTIDAD_SUBITEMS_X_ITEM
GO
CREATE FUNCTION FN_SOLMIN_OC_SUBITEM_RZOL39S_CANTIDAD_SUBITEMS_X_ITEM
( PNCCLNT NUMERIC(6),
  PSNORCML VARCHAR(35),
  PNNRITOC NUMERIC(6)
)
RETURNS NUMERIC(3)
LANGUAGE SQL
BEGIN
        DECLARE V_CANTIDAD NUMERIC(3)DEFAULT 0;
        SELECT COUNT(*) INTO V_CANTIDAD FROM RZOL39S WHERE CCLNT=PNCCLNT AND NORCML=PSNORCML AND NRITOC=PNNRITOC AND SESTRG<>'*';
        RETURN V_CANTIDAD;
END
GO
GRANT ALL PRIVILEGES ON FUNCTION FN_SOLMIN_OC_SUBITEM_RZOL39S_CANTIDAD_SUBITEMS_X_ITEM TO PUBLIC