DROP PROCEDURE SP_SOLMIN_TRACTO_RZST03_OBJ
GO
CREATE PROCEDURE SP_SOLMIN_TRACTO_RZST03_OBJ(
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_NPLCUN		VARCHAR(15),
		OUT	OU_MSGERR		VARCHAR(100)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN ATOMIC
--------------------------
-- Variables de Trabajo --
--------------------------
DECLARE strSQL  		VARCHAR(6000) DEFAULT '';
DECLARE	WK_SESTRG		VARCHAR(1) DEFAULT '';
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;

SET OU_MSGERR = '';

SELECT	IFNULL(MAX(SESTRG), '') INTO WK_SESTRG 
FROM	RZST03 WHERE CCMPN = IN_CCMPN AND NPLCUN = IN_NPLCUN;

-- Verificamos si existe el Tracto con las características proporcionadas
IF WK_SESTRG <> '' THEN
	IF WK_SESTRG <> '*' THEN
		SET strSQL = 'SELECT * FROM	RZST03 WHERE CCMPN = ? AND NPLCUN = ? ';
		PREPARE S1 FROM strSQL;
		OPEN CU_01 USING IN_CCMPN, IN_NPLCUN;
	ELSE
		SET OU_MSGERR = 'Tracto esta Anulado.';
	END IF;
ELSE
	SET OU_MSGERR = 'Tracto no existe.';
END IF;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_TRACTO_RZST03_OBJ TO PUBLIC 