DROP PROCEDURE SP_SOLMIN_ACOPLADO_POR_TRANSPORTISTA_RZST18_L01
GO
CREATE PROCEDURE SP_SOLMIN_ACOPLADO_POR_TRANSPORTISTA_RZST18_L01(
		IN	IN_NRUCTR		VARCHAR(15),
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_CDVSN		VARCHAR(1),
		IN	IN_CPLNDV		NUMERIC(3),
		IN	IN_NPLCAC		VARCHAR(256),
        IN	IN_TMRCVH		VARCHAR(256),
        IN	IN_TDEACP		VARCHAR(256),
		IN	IN_NROPAG		NUMERIC(6, 0),
		IN	IN_REGPAG		NUMERIC(6, 0),
		OUT	OU_TOTPAG		NUMERIC(6, 0)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE WK_TOTPAG			NUMERIC(6,0)		DEFAULT 0 ;	 -- NRO TOTAL DE PAGINAS SOBRE LA CONSULTA 
DECLARE WK_NPLCAC			VARCHAR(6)			DEFAULT ''; -- NUMERO DE ACOPLADO
DECLARE WK_CNTREG			NUMERIC(6,0)		DEFAULT 0 ;	 -- CONTADOR DE REGISTROS 
DECLARE WK_NRPAGS			NUMERIC(6,0)		DEFAULT 0 ;	 -- NRO DE PAGINAS EN TOTAL PARA LA CONSULTA ESTABLECIDA 

DECLARE STRSQL				VARCHAR(6000)		DEFAULT '' ; 
DECLARE STRSQL_FILTRO		VARCHAR(1000)		DEFAULT '' ; 
  
DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0 ; 
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1 ; 
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2 ; 
  
IF IN_REGPAG <= 0 THEN 
	SET IN_REGPAG = 1 ; 
END IF ; 

-- Filtros según Nro de ACOPLADO
IF IN_NPLCAC <> '' THEN 
	IF POSSTR ( IN_NPLCAC , ',' ) <> 0 THEN 
		SET IN_NPLCAC = REPLACE ( REPLACE ( IN_NPLCAC , ' ' , '' ) , ',' , ''',''' ); 
		SET STRSQL_FILTRO = ' AND NPLCAC IN  ( ''' || IN_NPLCAC || ''') ' ; 
	ELSE 
		IF POSSTR ( IN_NPLCAC , '*' ) <> 0 THEN 
			SET IN_NPLCAC = REPLACE ( IN_NPLCAC , '*' , '%' ) ; 
			SET STRSQL_FILTRO = ' AND Trim(NPLCAC) LIKE ''' || IN_NPLCAC || ''' ' ; 
		ELSE 
			SET STRSQL_FILTRO = ' AND NPLCAC = ''' || IN_NPLCAC || ''' ' ; 
		END IF ; 
	END IF ; 
END IF ; 
  
-- Filtros según Marca ACOPLADO
IF IN_TMRCVH <> '' THEN 
	IF POSSTR ( IN_TMRCVH , ',' ) <> 0 THEN 
		SET IN_TMRCVH = REPLACE ( REPLACE ( IN_TMRCVH , ' ' , '' ) , ',' , ''',''' ) ; 
		SET STRSQL_FILTRO = STRSQL_FILTRO || ' AND EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC AND TMRCVH IN  ( ''' || IN_TMRCVH || ''') ) ' ; 
	ELSE 
		IF POSSTR ( IN_TMRCVH , '*' ) <> 0 THEN 
			SET IN_TMRCVH = REPLACE ( IN_TMRCVH , '*' , '%' ) ; 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' AND EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC AND TMRCVH LIKE ''' || IN_TMRCVH || ''' ) ' ; 
		ELSE 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' AND EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC AND TMRCVH = ''' || IN_TMRCVH || ''' ) ' ; 
		END IF ; 
	END IF ; 
END IF ; 
  
-- Filtros según Detalle Tipo Acoplado
IF IN_TDEACP <> '' THEN 
	IF POSSTR ( IN_TDEACP , ',' ) <> 0 THEN 
		SET IN_TDEACP = REPLACE ( REPLACE ( IN_TDEACP , ' ' , '' ) , ',' , ''',''' ) ; 
		SET STRSQL_FILTRO = STRSQL_FILTRO || ' AND EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC '  || 
														 ' AND EXISTS( SELECT TDEACP FROM RZST04 WHERE CTIACP = RZST05.CTIACP AND TDEACP IN  ( ''' || IN_TDEACP || ''') ) )' ; 
	ELSE 
		IF POSSTR ( IN_TDEACP , '*' ) <> 0 THEN 
			SET IN_TDEACP = REPLACE ( IN_TDEACP , '*' , '%' ) ; 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' AND EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC ' || 
															 ' AND EXISTS( SELECT TDEACP FROM RZST04 WHERE CTIACP = RZST05.CTIACP AND Trim(TDEACP) LIKE ''' || IN_TDEACP || ''' ) ) ' ; 
		ELSE 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' AND EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC ' ||  
															 ' AND EXISTS( SELECT TDEACP FROM RZST04 WHERE CTIACP = RZST05.CTIACP AND TDEACP = ''' || IN_TDEACP || ''' ) ) ' ; 
		END IF ; 
	END IF ; 
END IF ; 

SET STRSQL = ' SELECT Count(NPLCAC) FROM RZST18 WHERE NRUCTR = ? AND CCMPN = ? AND CDVSN = ? AND CPLNDV = ? AND SESTAC <> ''*'' AND SESTRG <> ''*'' ' || STRSQL_FILTRO;	 
-- Preparamos el Macros que contiene la consulta de toda la información. 
PREPARE S0 FROM STRSQL ; 
OPEN CU_00 USING IN_NRUCTR, IN_CCMPN, IN_CDVSN, IN_CPLNDV; 
FETCH LAST FROM CU_00 INTO WK_TOTPAG ; 
CLOSE CU_00 ; 

IF IN_REGPAG <= 0 THEN 
	SET IN_REGPAG = 1;
	IF WK_TOTPAG > 0 THEN
		SET IN_REGPAG = WK_TOTPAG;
	END IF;
END IF;

IF WK_TOTPAG > 0 THEN
	IF MOD(WK_TOTPAG, IN_REGPAG) > 0 THEN
		SET WK_TOTPAG = INTEGER ( WK_TOTPAG / IN_REGPAG ) + 1;
	ELSE
		SET WK_TOTPAG = INTEGER ( WK_TOTPAG / IN_REGPAG );
	END IF;
ELSE
	SET WK_TOTPAG = 1;
END IF;

IF IN_NROPAG > WK_TOTPAG THEN
	SET IN_NROPAG = WK_TOTPAG;
END IF;

SET OU_TOTPAG = WK_TOTPAG;

SET STRSQL = ' SELECT NPLCAC FROM RZST18 WHERE NRUCTR = ? AND CCMPN = ? AND CDVSN = ? AND CPLNDV = ? AND SESTAC <> ''*'' AND SESTRG <> ''*'' and NPLCAC >= ?  ' || STRSQL_FILTRO || 
			 ' ORDER BY NPLCAC ASC FETCH FIRST ' || ( IN_REGPAG + 1 ) || ' ROWS ONLY ' ;	 
-- Preparamos el Macros que contiene la consulta de toda la información. 
PREPARE S1 FROM STRSQL ; 
-- Recorremos todas las páginas anteriores para obtener la última Orden de Compra 
WHILE WK_CNTREG < ( IN_NROPAG - 1 ) DO 
	OPEN CU_01 USING IN_NRUCTR, IN_CCMPN, IN_CDVSN, IN_CPLNDV, WK_NPLCAC ; 
	FETCH LAST FROM CU_01 INTO WK_NPLCAC ; 
	CLOSE CU_01 ; 
	 -- AVANZAMOS EL CONTADOR DE PAGINAS 
	SET WK_CNTREG = WK_CNTREG + 1 ; 
END WHILE ; 
-- Armamos la consulta final con toda la información 
SET STRSQL = ' SELECT NRUCTR, NPLCAC, ( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC ) TMRCVH, ' || 
				 ' ( SELECT Trim(TDEACP) FROM RZST04 WHERE EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC AND CTIACP = RZST04.CTIACP) ) TDEACP ' || 
			 ' FROM RZST18 WHERE NRUCTR = ? AND CCMPN = ? AND CDVSN = ? AND CPLNDV = ? AND SESTAC <> ''*'' AND SESTRG <> ''*'' and NPLCAC >= ? ' || STRSQL_FILTRO || 
			 ' ORDER BY NPLCAC ASC FETCH FIRST ' || IN_REGPAG || ' ROWS ONLY ' ; 
-- Realizamos la preparación de la Consulta para ser ejecutada 
PREPARE S2 FROM STRSQL ; 
OPEN CU_02 USING IN_NRUCTR, IN_CCMPN, IN_CDVSN, IN_CPLNDV, WK_NPLCAC ; 

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_ACOPLADO_POR_TRANSPORTISTA_RZST18_L01 TO PUBLIC 