DROP PROCEDURE SP_SOLMIN_CONDUCTOR_RZST08_L01
GO
CREATE PROCEDURE SP_SOLMIN_CONDUCTOR_RZST08_L01(
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_CBRCNT		VARCHAR(256),
        IN	IN_TNMCMC		VARCHAR(256),
        IN	IN_SINDRC		VARCHAR(256),
		IN	IN_NROPAG		NUMERIC(6, 0),
		IN	IN_REGPAG		NUMERIC(6, 0),
		OUT	OU_TOTPAG		NUMERIC(6, 0)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE WK_TOTPAG			NUMERIC ( 6 , 0 )	DEFAULT 0 ;	 -- NRO TOTAL DE PAGINAS SOBRE LA CONSULTA 
DECLARE WK_CBRCNT			VARCHAR(15)			DEFAULT '' ; -- NUMERO DE RUC DE LA EMPRESA DE TRANSPORTE
DECLARE WK_CNTREG			NUMERIC ( 6 , 0 )	DEFAULT 0 ;	 -- CONTADOR DE REGISTROS 
DECLARE WK_NRPAGS			NUMERIC ( 6 , 0 )	DEFAULT 0 ;	 -- NRO DE PAGINAS EN TOTAL PARA LA CONSULTA ESTABLECIDA 
  
DECLARE STRSQL				VARCHAR ( 6000 )	DEFAULT '' ; 
DECLARE STRSQL_FILTRO		VARCHAR ( 1000 )	DEFAULT '' ; 
  
DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0 ; 
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1 ; 
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2 ; 
  
IF IN_REGPAG <= 0 THEN 
	SET IN_REGPAG = 1 ; 
END IF ; 
  
-- Filtros según RUC de la Empresa  de Transporte
IF IN_CBRCNT <> '' THEN 
	IF POSSTR ( IN_CBRCNT , ',' ) <> 0 THEN 
		SET IN_CBRCNT = REPLACE ( REPLACE ( IN_CBRCNT , ' ' , '' ) , ',' , ''',''' ); 
		SET STRSQL_FILTRO = ' And CBRCNT IN  ( ''' || IN_CBRCNT || ''') ' ; 
	ELSE 
		IF POSSTR ( IN_CBRCNT , '*' ) <> 0 THEN 
			SET IN_CBRCNT = REPLACE ( IN_CBRCNT , '*' , '%' ) ; 
			SET STRSQL_FILTRO = ' And Trim(CBRCNT) LIKE ''' || IN_CBRCNT || ''' ' ; 
		ELSE 
			SET STRSQL_FILTRO = ' And CBRCNT = ''' || IN_CBRCNT || ''' ' ; 
		END IF ; 
	END IF ; 
END IF ; 
  
-- Filtros según Razón Social 
IF IN_TNMCMC <> '' THEN 
	IF POSSTR ( IN_TNMCMC , ',' ) <> 0 THEN 
		SET IN_TNMCMC = REPLACE ( Trim( IN_TNMCMC ), ',' , ''',''' ) ; 
		SET STRSQL_FILTRO = STRSQL_FILTRO || ' And ( Trim( TNMCMC ) || '' '' || Trim( APEPAT ) || '' '' || Trim( APEMAT ) ) IN  ( ''' || IN_TNMCMC || ''') ' ; 
	ELSE 
		IF POSSTR ( IN_TNMCMC , '*' ) <> 0 THEN 
			SET IN_TNMCMC = REPLACE ( IN_TNMCMC , '*' , '%' ) ; 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' And ( Trim( TNMCMC ) || '' '' || Trim( APEPAT ) || '' '' || Trim( APEMAT ) ) LIKE ''' || IN_TNMCMC || ''' ' ; 
		ELSE 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' And ( Trim( TNMCMC ) || '' '' || Trim( APEPAT ) || '' '' || Trim( APEMAT ) ) = ''' || IN_TNMCMC || ''' ' ; 
		END IF ; 
	END IF ; 
END IF ; 
  
-- Filtros según Código de le Empresa de Transporte
IF IN_SINDRC <> '' THEN 
	IF POSSTR ( IN_SINDRC , ',' ) <> 0 THEN 
		SET IN_SINDRC = REPLACE ( IN_SINDRC , ' ' , '' ) ; 
		SET STRSQL_FILTRO = STRSQL_FILTRO || ' And SINDRC IN  ( ''' || IN_SINDRC || ''') ' ; 
	ELSE 
		IF POSSTR ( IN_SINDRC , '*' ) <> 0 THEN 
			SET IN_SINDRC = REPLACE ( IN_SINDRC , '*' , '%' ) ; 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' And Trim(SINDRC) LIKE ''' || IN_SINDRC || ''' ' ; 
		ELSE 
			SET STRSQL_FILTRO = STRSQL_FILTRO || ' And SINDRC = ''' || IN_SINDRC || ''' ' ; 
		END IF ; 
	END IF ; 
END IF ; 

SET STRSQL = ' SELECT Count(CBRCNT) FROM RZST08 WHERE CCMPN = ? AND SESTRG <> ''*'' ' || STRSQL_FILTRO;	 
-- Preparamos el Macros que contiene la consulta de toda la información. 
PREPARE S0 FROM STRSQL ; 
OPEN CU_00 USING IN_CCMPN; 
FETCH LAST FROM CU_00 INTO WK_TOTPAG ; 
CLOSE CU_00 ; 

IF IN_REGPAG <= 0 THEN 
	SET IN_REGPAG = 1;
	IF WK_TOTPAG > 0 THEN
		SET IN_REGPAG = WK_TOTPAG;
	END IF;
END IF;

IF WK_TOTPAG > 0 THEN
	IF MOD(WK_TOTPAG, IN_REGPAG) > 0 THEN
		SET WK_TOTPAG = INTEGER ( WK_TOTPAG / IN_REGPAG ) + 1;
	ELSE
		SET WK_TOTPAG = INTEGER ( WK_TOTPAG / IN_REGPAG );
	END IF;
ELSE
	SET WK_TOTPAG = 1;
END IF;

IF IN_NROPAG > WK_TOTPAG THEN
	SET IN_NROPAG = WK_TOTPAG;
END IF;

SET OU_TOTPAG = WK_TOTPAG;

SET STRSQL = ' SELECT CBRCNT FROM RZST08 WHERE CCMPN = ? AND SESTRG <> ''*'' AND CBRCNT >= ?  ' || STRSQL_FILTRO || 
			 ' ORDER BY CBRCNT ASC FETCH FIRST ' || ( IN_REGPAG + 1 ) || ' ROWS ONLY ' ;	 
-- Preparamos el Macros que contiene la consulta de toda la información. 
PREPARE S1 FROM STRSQL ; 
-- Recorremos todas las páginas anteriores para obtener la última Orden de Compra 
WHILE WK_CNTREG < ( IN_NROPAG - 1 ) DO 
	OPEN CU_01 USING IN_CCMPN, WK_CBRCNT ; 
	FETCH LAST FROM CU_01 INTO WK_CBRCNT ; 
	CLOSE CU_01 ; 
	 -- AVANZAMOS EL CONTADOR DE PAGINAS 
	SET WK_CNTREG = WK_CNTREG + 1 ; 
END WHILE ; 
-- Armamos la consulta final con toda la información 
SET STRSQL = ' SELECT CBRCNT, TNMCMC, APEPAT, APEMAT, SINDRC FROM RZST08 WHERE CCMPN = ? AND SESTRG <> ''*'' and CBRCNT >= ? ' || STRSQL_FILTRO || 
			 ' ORDER BY CBRCNT ASC FETCH FIRST ' || IN_REGPAG || ' ROWS ONLY ' ; 
-- Realizamos la preparación de la Consulta para ser ejecutada 
PREPARE S2 FROM STRSQL ; 
OPEN CU_02 USING IN_CCMPN, WK_CBRCNT ; 

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_CONDUCTOR_RZST08_L01 TO PUBLIC