DROP PROCEDURE SP_SOLMIN_TRANSPORTISTA_RZST01_OBJ
GO
CREATE PROCEDURE SP_SOLMIN_TRANSPORTISTA_RZST01_OBJ(
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_NRUCTR		VARCHAR(15),
		OUT OU_MSGERR		VARCHAR(100)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN ATOMIC
--------------------------
-- Variables de Trabajo --
--------------------------
DECLARE strSQL  		VARCHAR(6000) DEFAULT '';
DECLARE	WK_SESTRG		VARCHAR(1) DEFAULT '';
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;

SET OU_MSGERR = '';

SELECT	IFNULL(MAX(SESTRG), '') INTO WK_SESTRG 
FROM	RZST01 WHERE NRUCTR = IN_NRUCTR AND CCMPN = IN_CCMPN;

-- Verificamos 	si existe la Empresa Transportista con las características proporcionadas
IF WK_SESTRG <> '' THEN
	IF WK_SESTRG <> '*' THEN
		SET strSQL = 'SELECT * FROM	RZST01 WHERE NRUCTR = ? AND CCMPN = ?';
		PREPARE S1 FROM strSQL;
		OPEN CU_01 USING IN_NRUCTR, IN_CCMPN;
	ELSE
		SET OU_MSGERR = 'Transportista esta Anulado.';
	END IF;
ELSE
	SET OU_MSGERR = 'Transportista no existe.';
END IF;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_TRANSPORTISTA_RZST01_OBJ TO PUBLIC