DROP PROCEDURE SP_SOLMIN_ACOPLADO_POR_TRANSPORTISTA_RZST18_OBJ
GO
CREATE PROCEDURE SP_SOLMIN_ACOPLADO_POR_TRANSPORTISTA_RZST18_OBJ(
		IN	IN_NRUCTR		VARCHAR(15),
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_CDVSN		VARCHAR(1),
		IN	IN_CPLNDV		NUMERIC(3),
		IN	IN_NPLCAC		VARCHAR(15),
		OUT	OU_MSGERR		VARCHAR(100)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN ATOMIC
--------------------------
-- Variables de Trabajo --
--------------------------
DECLARE strSQL  		VARCHAR(6000) DEFAULT '';
DECLARE	WK_SESTRG		VARCHAR(1) DEFAULT '';
DECLARE	WK_SESTAC		VARCHAR(1) DEFAULT '';

DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;

SET OU_MSGERR = '';

SELECT	IFNULL(MAX(SESTAC), ''), IFNULL(MAX(SESTRG), '') INTO WK_SESTAC, WK_SESTRG 
FROM	RZST18 WHERE NRUCTR = IN_NRUCTR AND CCMPN = IN_CCMPN AND CDVSN = IN_CDVSN AND CPLNDV = IN_CPLNDV AND NPLCAC = IN_NPLCAC;

-- Verificamos si existe el Acoplado con las características proporcionadas
IF WK_SESTRG <> '' THEN
	IF WK_SESTRG <> '*' THEN
		IF WK_SESTAC = '*' THEN
			SET OU_MSGERR = 'Acoplado no le pertenece actualmente al Transportista.';
		ELSE
			SET strSQL =' SELECT NRUCTR, CCMPN, CDVSN, CPLNDV, NPLCAC, NumberToDate(FECINI) FECINI, NumberToDate(FECFIN) FECFIN, TOBS, SESTAC, SESTRG, ' ||
							 ' ( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC ) TMRCVH, ' || 
							 ' ( SELECT TDEACP FROM RZST04 WHERE EXISTS( SELECT TMRCVH FROM RZST05 WHERE NPLCAC = RZST18.NPLCAC AND CTIACP = RZST04.CTIACP) ) TDEACP ' ||
						 'FROM	RZST18 WHERE NRUCTR = ? AND CCMPN = ? AND CDVSN = ? AND CPLNDV = ? AND NPLCAC = ? ';
			PREPARE S1 FROM strSQL;
			OPEN CU_01 USING IN_NRUCTR, IN_CCMPN, IN_CDVSN, IN_CPLNDV, IN_NPLCAC;
		END IF;
	ELSE
		SET OU_MSGERR = 'Acoplado esta Anulado.';
	END IF;
ELSE
	SET OU_MSGERR = 'Acoplado no existe.';
END IF;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_ACOPLADO_POR_TRANSPORTISTA_RZST18_OBJ TO PUBLIC   