DROP PROCEDURE SP_SOLMIN_TRACTO_POR_TRANSPORTISTA_RZST17_OBJ
GO
CREATE PROCEDURE SP_SOLMIN_TRACTO_POR_TRANSPORTISTA_RZST17_OBJ(
		IN	IN_NRUCTR		VARCHAR(15),
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_CDVSN		VARCHAR(1),
		IN	IN_CPLNDV		NUMERIC(3),
		IN	IN_NPLCUN		VARCHAR(15),
		OUT	OU_MSGERR		VARCHAR(100)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN ATOMIC
--------------------------
-- Variables de Trabajo --
--------------------------
DECLARE strSQL  		VARCHAR(6000) DEFAULT '';
DECLARE	WK_SESTRG		VARCHAR(1) DEFAULT '';
DECLARE	WK_SESTCM		VARCHAR(1) DEFAULT '';
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;

SET OU_MSGERR = '';

SELECT	IFNULL(MAX(SESTCM), ''), IFNULL(MAX(SESTRG), '') INTO WK_SESTCM, WK_SESTRG 
FROM	RZST17 WHERE NRUCTR = IN_NRUCTR AND CCMPN = IN_CCMPN AND CDVSN = IN_CDVSN AND CPLNDV = IN_CPLNDV AND NPLCUN = IN_NPLCUN;

-- Verificamos si existe el Tracto con las características proporcionadas
IF WK_SESTRG <> '' THEN
	IF WK_SESTRG <> '*' THEN
		IF WK_SESTCM = '*' THEN
			SET OU_MSGERR = 'Tracto no le pertenece actualmente al Transportista.';
		ELSE
			SET strSQL = 'SELECT NRUCTR, NPLCUN, NumberToDate(FECINI) as FECINI, NumberToDate(FECFIN) as FECFIN, NPLACP, CBRCND, CTPCRA, CCLNT, TOBS, SESTCM, SESTRG, ' ||
							 ' ( SELECT TMRCTR FROM RZST03 WHERE NPLCUN = RZST17.NPLCUN ) TMRCTR, ' || 
							 ' ( SELECT NRGMT1 FROM RZST03 WHERE NPLCUN = RZST17.NPLCUN ) NRGMT1 ' ||
						 'FROM	RZST17 WHERE NRUCTR = ? AND CCMPN = ? AND CDVSN = ? AND CPLNDV = ? AND NPLCUN = ? ';
			PREPARE S1 FROM strSQL;
			OPEN CU_01 USING IN_NRUCTR, IN_CCMPN, IN_CDVSN, IN_CPLNDV, IN_NPLCUN;
		END IF;
	ELSE
		SET OU_MSGERR = 'Tracto esta Anulado.';
	END IF;
ELSE
	SET OU_MSGERR = 'Tracto no existe.';
END IF;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_TRACTO_POR_TRANSPORTISTA_RZST17_OBJ TO PUBLIC  