DROP PROCEDURE SP_SOLMIN_ACOPLADO_RZST05_OBJ
GO
CREATE PROCEDURE SP_SOLMIN_ACOPLADO_RZST05_OBJ(
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_NPLCAC		VARCHAR(15),
		OUT	OU_MSGERR		VARCHAR(100)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN ATOMIC
--------------------------
-- Variables de Trabajo --
--------------------------
DECLARE strSQL  		VARCHAR(6000) DEFAULT '';
DECLARE	WK_SESTRG		VARCHAR(1) DEFAULT '';
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;

SET OU_MSGERR = '';

SELECT	IFNULL(MAX(SESTRG), '') INTO WK_SESTRG 
FROM	RZST05 WHERE CCMPN = IN_CCMPN AND NPLCAC = IN_NPLCAC;

-- Verificamos si existe el Acoplado con las características proporcionadas
IF WK_SESTRG <> '' THEN
	IF WK_SESTRG <> '*' THEN
		SET strSQL = 'SELECT RZST05.*, ( SELECT TDEACP FROM RZST04 WHERE CTIACP = RZST05.CTIACP ) TDEACP FROM RZST05 WHERE CCMPN = ? AND NPLCAC = ? ';
		PREPARE S1 FROM strSQL;
		OPEN CU_01 USING IN_CCMPN, IN_NPLCAC;
	ELSE
		SET OU_MSGERR = 'Acoplado esta Anulado.';
	END IF;
ELSE
	SET OU_MSGERR = 'Acoplado no existe.';
END IF;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_ACOPLADO_RZST05_OBJ TO PUBLIC  