--------------------------------------------------
-- REPORTE DE INVENTARIO DE ALMACEN DE TRANSITO --
--------------------------------------------------
-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL65_R01
GO
CREATE PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL65_R01(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_FINVE		NUMERIC(8, 0),
		IN	IN_TUBRFR		VARCHAR(17),
		IN	IN_STPING		VARCHAR(1)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0;

SET strSQL ='	SELECT	RZ65.TUBRFR, 
						RZ65.CREFFW, 
						NumberToDate( RZ65.FINGAL ) FINGAL,
						RZ65.QREFFW, 
						RZ65.TIPBTO, 
						RZ65.QPSOBL,
						RZ65.QVLBTO,
						TRIM(RZ38.TTINTC) AS TTINTC,
						RZ05.TPRVCL,
						RZ65.QAROCP, 
						RZ38.TNOMCOM,
						
						RZ66.NORCML, 
						RZ66.NRITOC, 
						RZ39.TDITES,
						RZ39.IVUNIT, 
						RZ66.QBLTSR QSLCNB, 
						RZ39.TUNDIT,
						RZ66.QPEPQT, 
						RZ66.QVOPQT, 
  						RZ66.NGRPRV, 
						RZ39.TLUGEN
				FROM	RZOL65	RZ65
						INNER JOIN RZOL66 RZ66
							ON	RZ65.CCLNT	= ' || IN_CCLNT || ' 
							AND	RZ65.CCLNT	= RZ66.CCLNT
							AND	RZ65.CREFFW = RZ66.CREFFW
							AND	RZ65.SESTRG <> ''*''
							AND	RZ66.SESTRG <> ''*''
							AND	RZ65.FREFFW <= ' || IN_FINVE || ' 
							AND	( ( RZ65.FSLFFW = 0  )	OR
								  ( RZ65.FSLFFW <> 0	AND	RZ65.FSLFFW > ' || IN_FINVE || '  ) )
							AND	RZ66.QBLTSR <> 0
						INNER JOIN RZOL38 RZ38
							ON	RZ66.CCLNT  = RZ38.CCLNT
							AND	RZ66.NORCML = RZ38.NORCML
							AND	RZ38.SESTRG <> ''*''
						INNER JOIN RZOL39 RZ39
							ON	RZ66.CCLNT  = RZ39.CCLNT
							AND	RZ66.NORCML = RZ39.NORCML
							AND	RZ66.NRITOC = RZ39.NRITOC
							AND	RZ39.SESTRG <> ''*''
						INNER JOIN RZOL05 RZ05
							ON	RZ05.CPRVCL = RZ38.CPRVCL ';
IF IN_TUBRFR <> '' THEN
	SET	strSQL = strSQL || ' Where   Trim( RZ65.TUBRFR ) = ''' || IN_TUBRFR || ''' ';
END IF;
IF IN_STPING <> '' THEN
	SET	strSQL = strSQL || ' Where   Trim( RZ65.STPING ) = ''' || IN_STPING || ''' ';
END IF;
SET strSQL = strSQL || ' Order By RZ65.TUBRFR, RZ65.CREFFW, RZ66.NORCML, RZ66.NRITOC ';
		
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S0 FROM strSQL;
OPEN CU_00;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL65_R01 TO PUBLIC