DROP PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL66_L05
GO
CREATE PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL66_L05(
		IN	IN_CCLNT			NUMERIC(6,0),
		IN	IN_CREFFW			VARCHAR(256),
		IN	IN_FSLFFW_INI		VARCHAR(10),
		IN	IN_FSLFFW_FIN		VARCHAR(10),
		IN	IN_TUBRFR			VARCHAR(20),
		IN	IN_STRNSM			VARCHAR(1),
		IN	IN_TTINTC			VARCHAR(6),
		IN	IN_STUPDT			VARCHAR(1),
		IN	IN_MMCUSR			VARCHAR(10)
        )
RESULT SETS 2
LANGUAGE SQL
BEGIN
--------------------------------------
-- Variables de Trabajo - Seguridad --
--------------------------------------
DECLARE WK_QRYSQL  	VARCHAR(6000)	DEFAULT '';
DECLARE WK_WHRSQL  	VARCHAR(1000)	DEFAULT '';

DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2;
DECLARE CU_03 SCROLL CURSOR WITH RETURN FOR S3;

-- Clase Almacén : Listado de Ingresos de Bultos al Almacén
SET WK_QRYSQL ='DECLARE Global Temporary Table Session.Despacho AS(
				Select	Trim( R66.NORCML ) NORCML,
						R66.NRITOC,
					  (	SELECT Trim( CINTER ) FROM MMUSCL WHERE MMCUSR = ''' || IN_MMCUSR || ''' AND CCLNT = R65.CCLNT ) CINTER,
					  ( SELECT Trim( TLUGEN ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) WARHOU,
						Trim( R65.CREFFW ) CREFFW, R65.FSLFFW, R65.CRTLTE, R66.NMNFTF,
					  	NumberToDate(R65.FSLFFW) + 2 DAYS  DSLFFW,
					  ( SELECT Trim( TUNDIT ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) ELLUIO,	
						R66.QBLTSR,
						Trim( R66.NGRPRV ) NGRPRV,
						R65.FREFFW,
						Trim( R65.DESCWB ) DESCWB,
						R65.QREFFW,
						Trim( R65.TIPBTO ) TIPBTO,
						R65.QPSOBL, Trim(R65.TUBRFR) TUBRFR,
					  ( SELECT Trim( TCITCL ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) TCITCL,
					  ( SELECT Trim( TRFRN  ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) TRFRN,
					  ( SELECT Trim( TRFRNA ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) TRFRNA,
					  ( SELECT Trim( TRFRNB ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) TRFRNB,
					  ( SELECT Trim( TRFRN1 ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) TRFRN1,
					  ( SELECT Trim( TRFRN2 ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) TRFRN2,
					  ( SELECT Trim( TRFRN3 ) FROM RZOL39 WHERE NORCML = R66.NORCML AND RZOL39.NRITOC = R66.NRITOC AND RZOL39.CCLNT = R66.CCLNT ) TRFRN3
				From    RZOL65 R65 INNER JOIN RZOL66 R66 ON  R65.CCLNT  = R66.CCLNT
														 AND R65.CREFFW = R66.CREFFW
				Where   R65.CCLNT =  ' || IN_CCLNT || '
				and		R65.SESTRG <> ''*'' 
				and		R65.STPING = ''C''
				and		R66.SESTRG <> ''*'' ' ;

IF IN_CREFFW <> '' THEN
	IF POSSTR( IN_CREFFW, ',') <> 0 THEN
		SET IN_CREFFW = REPLACE( IN_CREFFW, ',', ''',''');
		SET WK_QRYSQL = WK_QRYSQL || ' And R65.CREFFW IN  ( '''  || IN_CREFFW || ''') ' ;
	ELSE
		SET IN_CREFFW = REPLACE( IN_CREFFW, '*', '%');
		SET WK_QRYSQL = WK_QRYSQL || ' And Trim( R65.CREFFW ) LIKE '''  || IN_CREFFW || ''' ' ;
	END IF;
END IF;
IF IN_FSLFFW_INI <> '' THEN
	SET WK_QRYSQL = WK_QRYSQL || ' And R65.FSLFFW >= '  || IN_FSLFFW_INI || ' ' ;
END IF;
IF IN_FSLFFW_FIN <> '' THEN
	SET WK_QRYSQL = WK_QRYSQL || ' And R65.FSLFFW <= '  || IN_FSLFFW_FIN || ' ' ;
END IF;
IF IN_TUBRFR <> '' THEN
	SET WK_QRYSQL = WK_QRYSQL || ' And Trim(R65.TUBRFR) = '''  || IN_TUBRFR || ''' ' ;
END IF;
-- Filtros según Status de Transmisión
CASE IN_STRNSM
	-- Pendiente de Envio para recepción
	WHEN 'P' THEN 
		SET WK_QRYSQL = WK_QRYSQL || ' And R65.STRNSM = '''' ' ;
	-- Pendiente de Envio para recepción + Enviados
	WHEN 'R' THEN
		SET WK_QRYSQL = WK_QRYSQL || ' And R65.STRNSM in ('''', ''1'') ' ;
	-- Pendiente de Envio para Despacho
	WHEN 'D' THEN
		SET WK_QRYSQL = WK_QRYSQL || ' And R65.STRNSM = ''1'' ' ;
	-- Pendiente de Envio para Despacho + Enviados
	WHEN 'E' THEN
		SET WK_QRYSQL = WK_QRYSQL || ' And R65.STRNSM in (''1'', ''2'') ' ;
	ELSE
		SET WK_QRYSQL = WK_QRYSQL;
END CASE;
IF IN_TTINTC <> '' THEN
	SET WK_QRYSQL = WK_QRYSQL || ' And Exists(	SELECT	NORCML 
												FROM	RZOL38 WHERE RZOL38.CCLNT = R66.CCLNT AND RZOL38.NORCML = R66.NORCML 
												AND		RZOL38.TTINTC = ''' || IN_TTINTC || ''' )';
END IF;
SET WK_QRYSQL = WK_QRYSQL || ' ) WITH DATA WITH REPLACE ';

PREPARE dclstmt FROM WK_QRYSQL;
EXECUTE dclstmt;

-- Actualizamos la información enviada si el status IN_STUPDT es igual 'S'
IF IN_STUPDT = 'S' THEN
	UPDATE	RZOL65 
	SET		STRNSM = '2'
	WHERE	CCLNT = IN_CCLNT 
	AND		CREFFW IN ( SELECT t1.CREFFW FROM Session.Despacho t1);
END IF;

-- Realizamos la preparación de la Consulta para ser ejecutada
CASE 
	WHEN IN_CCLNT = 9425 THEN
		SET WK_QRYSQL = ' DISTINCT NMNFTF, CREFFW, FSLFFW, (YEAR(DSLFFW) * 10000 + MONTH(DSLFFW) * 100 + DAY(DSLFFW)) TMPDT1, CRTLTE ';
	WHEN IN_CCLNT = 2287 THEN 
		SET WK_QRYSQL = ' DISTINCT NMNFTF, CREFFW, FSLFFW, (YEAR(DSLFFW) * 10000 + MONTH(DSLFFW) * 100 + DAY(DSLFFW)) TMPDT1, CRTLTE ';
	WHEN IN_CCLNT = 44871 OR IN_CCLNT = 46550 OR IN_CCLNT = 48623 OR IN_CCLNT = 48622 THEN 
		SET WK_QRYSQL = 'NORCML, TCITCL, '''', Case When QBLTSR - Decimal(QBLTSR,15,0) = 0 Then Trim(Decimal(QBLTSR,15,0)) ' ||
												  '	When QBLTSR - Decimal(QBLTSR,15,0) > 0 and Decimal(QBLTSR,15,2) = 0 Then Trim(Decimal(QBLTSR,15,0)) ' ||
												  '	Else Trim(Decimal(QBLTSR,15,2)) End, ' ||
								' '''', NumberToDate(FSLFFW) FSLFFW, TRFRN, 1101, ''0202'', TRFRNA, TRFRNB, TRFRN1 ';
		SET WK_WHRSQL = 'WHERE Trim(TCITCL) <> '''' ';
	ELSE
		SET WK_QRYSQL = ' * ';
END CASE;

SET WK_QRYSQL = ' SELECT ' || WK_QRYSQL || ' FROM Session.Despacho ' || WK_WHRSQL || ' ORDER BY 1, 2 ';

-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S2 FROM WK_QRYSQL;
OPEN CU_02;

-- Limpiamos el contenido de las variables
SET WK_QRYSQL = '';
SET WK_WHRSQL = '';
-- Realizamos la preparación de la Consulta para ser ejecutada
CASE 
	WHEN IN_CCLNT = 44871 OR IN_CCLNT = 46550 OR IN_CCLNT = 48623 OR IN_CCLNT = 48622 THEN 
		SET WK_QRYSQL = 'NORCML, TCITCL, '''', Case When QBLTSR - Decimal(QBLTSR,15,0) = 0 Then Trim(Decimal(QBLTSR,15,0)) ' ||
												  '	When QBLTSR - Decimal(QBLTSR,15,0) > 0 and Decimal(QBLTSR,15,2) = 0 Then Trim(Decimal(QBLTSR,15,0)) ' ||
												  '	Else Trim(Decimal(QBLTSR,15,2)) End, ' ||
								' '''', NumberToDate(FSLFFW) FSLFFW, TRFRN, 1101, ''0202'', TRFRNA, TRFRNB, TRFRN1 ';
		SET WK_WHRSQL = 'WHERE Trim(TCITCL) = '''' ';
	ELSE
		SET WK_QRYSQL = '';
END CASE;

IF WK_QRYSQL <> '' THEN 
	SET WK_QRYSQL = ' SELECT ' || WK_QRYSQL || ' FROM Session.Despacho ' || WK_WHRSQL || ' ORDER BY 1, 2 ';

	PREPARE S3 FROM WK_QRYSQL;
	OPEN CU_03;
END IF;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL66_L05 TO PUBLIC	