-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SAT_BULTO_RZOL65_Q01
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SAT_BULTO_RZOL65_Q01(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_CREFFW		VARCHAR(20)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE WK_SSTINV			VARCHAR(1)		DEFAULT '0';	-- EN STOCK DE ALMACEN
DECLARE WK_SESTRG			VARCHAR(1)		DEFAULT '*';	-- EN STOCK DE ALMACEN
DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0;


-- Armamos la consulta final con toda la información
SET strSQL = '	SELECT	RZOL65.CREFFW, Max( RZOL65.QREFFW ) AS QREFFW, 
						Max( (	SELECT	NROPLT 
								FROM	RZOL65Q 
								WHERE	CCLNT  = RZOL65.CCLNT 
								AND		CREFFW = RZOL65.CREFFW ) ) as NROPLT,
						Max( (	SELECT	TLUGEN 
								FROM	RZOL39  
								WHERE	CCLNT  = RZOL66.CCLNT 
								AND		NORCML = RZOL66.NORCML 
								AND		NRITOC = RZOL66.NRITOC ) ) AS TLUGEN,
						Count( Distinct (	SELECT	TLUGEN 
											FROM	RZOL39
											WHERE	CCLNT  = RZOL66.CCLNT 
											AND		NORCML = RZOL66.NORCML 
											AND		NRITOC = RZOL66.NRITOC ) ) AS NOCURR
				FROM	RZOL65 INNER JOIN RZOL66 ON  RZOL65.CCLNT  = RZOL66.CCLNT
												 AND RZOL65.CREFFW = RZOL66.CREFFW
				WHERE	RZOL65.CREFFW = ? And RZOL65.CCLNT = ? And RZOL65.SSTINV = ? 
				AND		RZOL65.SESTRG <> ? AND RZOL66.SESTRG <> ?
				GROUP BY RZOL65.CREFFW ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S0 FROM strSQL;
OPEN CU_00 USING IN_CREFFW, IN_CCLNT, WK_SSTINV, WK_SESTRG, WK_SESTRG;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL65_Q01 TO PUBLIC