-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SAT_BULTO_RZOL65_DEL
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SAT_BULTO_RZOL65_DEL(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_CREFFW		VARCHAR(20),
		IN  IN_USUARI  		VARCHAR(10),
		OUT	OU_MSGERR		VARCHAR(200)	-- Mensaje de Error
        )
RESULT SETS 0
LANGUAGE SQL
BEGIN ATOMIC
	--------------------------------------
	-- Variables de Trabajo - Seguridad --
	--------------------------------------
	DECLARE	WK_FECHA	NUMERIC(10, 0)	DEFAULT 0;
	DECLARE	WK_HORA		NUMERIC(10, 0)	DEFAULT 0;
	--------------------------
	-- Variables de Trabajo --
	--------------------------
	DECLARE WK_CREFFW	VARCHAR(20)		DEFAULT '';
	DECLARE WK_SESTRG	VARCHAR(1)		DEFAULT '';
	DECLARE WK_SSTINV	VARCHAR(1)		DEFAULT '';
	DECLARE WK_STRNSM	VARCHAR(1)		DEFAULT '';
	
	-- Obtengo la fecha y hora actual
	SET	WK_FECHA = YEAR(CURRENT DATE) * 10000 + MONTH(CURRENT DATE) * 100 + DAY(CURRENT DATE);
	SET	WK_HORA  = HOUR(CURRENT TIME) * 10000 + MINUTE(CURRENT TIME) * 100 + SECOND(CURRENT TIME);
	SET OU_MSGERR = '';
	
	SELECT	CREFFW, SESTRG, SSTINV, 'N' --STRNSM
	INTO	WK_CREFFW, WK_SESTRG, WK_SSTINV, WK_STRNSM
	FROM	RZOL65 
	WHERE	CCLNT = IN_CCLNT 
	AND		CREFFW = IN_CREFFW;
	
	IF WK_CREFFW <> '' THEN
		IF WK_SESTRG <> '*' THEN
			IF WK_SSTINV = '0' THEN
				IF WK_STRNSM = 'N' THEN
					IF NOT EXISTS( SELECT CREFFW FROM RZOL66 WHERE CCLNT = IN_CCLNT AND CREFFW = IN_CREFFW AND SESTRG <> '*' ) THEN
						UPDATE	RZOL65
						SET		SESTRG = '*',
								CULUSA = IN_USUARI,
								FULTAC = WK_FECHA,
								HULTAC = WK_HORA,
								UPDATE_IDENT = UPDATE_IDENT + 1
						WHERE	CCLNT  = IN_CCLNT 
						AND		CREFFW = IN_CREFFW;
					ELSE
						SET OU_MSGERR = 'El Bulto posee Item(s) que permanecen ACTIVOS.';
					END IF;
				ELSE
					SET OU_MSGERR = 'El Bulto no puede eliminarse, debido a que la información ya fue TRANSFERIDA al Cliente.';
				END IF;
			ELSE
				SET OU_MSGERR = 'Bulto no se encuentra en STOCK.';
			END IF;
		ELSE
			SET OU_MSGERR = 'Bulto ya se encuentra ANULADO.';
		END IF;
	ELSE
		SET OU_MSGERR = 'Bulto no existe.';
	END IF;	
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SAT_BULTO_RZOL65_DEL TO PUBLIC