-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC32_DEL
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC32_DEL(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NPRALM		NUMERIC(10, 0),
        IN  IN_USUARI  		VARCHAR(10),
		OUT OU_MSGERR		VARCHAR(200)	-- Mensaje de Error
        )
RESULT SETS 0
LANGUAGE SQL
BEGIN ATOMIC
	--------------------------------------
	-- Variables de Trabajo - Seguridad --
	--------------------------------------
	DECLARE	WK_FECHA	NUMERIC(10, 0)	DEFAULT 0;
	DECLARE	WK_HORA		NUMERIC(10, 0)	DEFAULT 0;
	--------------------------
	-- Variables de Trabajo --
	--------------------------

	-- Obtengo la fecha y hora actual
	SET	WK_FECHA = YEAR(CURRENT DATE) * 10000 + MONTH(CURRENT DATE) * 100 + DAY(CURRENT DATE);
	SET	WK_HORA  = HOUR(CURRENT TIME) * 10000 + MINUTE(CURRENT TIME) * 100 + SECOND(CURRENT TIME);
	SET OU_MSGERR = '';

	IF EXISTS( SELECT NPRALM FROM RZSC32 WHERE NPRALM = IN_NPRALM AND STPOFC = 'P' ) THEN
		Update	RZSC32
		Set		SESTRG = '*',
				CULUSA = IN_USUARI,
				FULTAC = WK_FECHA,
				HULTAC = WK_HORA,
				UPDATE_IDENT = UPDATE_IDENT + 1
		Where	NPRALM = IN_NPRALM
		and		CCLNT  = IN_CCLNT;
		
		Update	RZSC33
		Set		SESTRG = '*',
				CULUSA = IN_USUARI,
				FULTAC = WK_FECHA,
				HULTAC = WK_HORA,
				UPDATE_IDENT = UPDATE_IDENT + 1
		Where	NPRALM = IN_NPRALM
		AND		CCLNT  = IN_CCLNT;
	ELSE
		SET OU_MSGERR = 'Información no puede ser Eliminada.';
	END IF;
END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_ALMACENAJE_RZSC32_DEL TO PUBLIC