-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SA_SERVICIOS_RZSC30_L01
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SA_SERVICIOS_RZSC30_L01(
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_CDVSN		VARCHAR(1),
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NOPRCN		VARCHAR(256),
		IN	IN_STPODP		VARCHAR(1),
		IN	IN_CSRVNV		VARCHAR(256),
		IN	IN_FECINI		NUMERIC(8, 0),
		IN	IN_FECFIN		NUMERIC(8, 0),
		IN	IN_NROPAG		NUMERIC(6, 0),
		IN	IN_REGPAG		NUMERIC(6, 0),
		OUT OU_TOTPAG		NUMERIC(6, 0)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE WK_TOTPAG			NUMERIC(6, 0)	DEFAULT 0;	-- NRO TOTAL DE PAGINAS SOBRE LA CONSULTA
DECLARE WK_NOPRCN			NUMERIC(10,0)	DEFAULT 0;	-- NRO DE OPERACION TEMPORAL
DECLARE WK_CNTREG			NUMERIC(6, 0)	DEFAULT 0;	-- CONTADOR DE REGISTROS
DECLARE WK_NRPAGS			NUMERIC(6, 0)	DEFAULT 0;	-- NRO DE PAGINAS EN TOTAL PARA LA CONSULTA ESTABLECIDA 

DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE strSQL_NOPRCN		VARCHAR(300)	DEFAULT '';
DECLARE strSQL_CSRVNV		VARCHAR(500)	DEFAULT '';
DECLARE strSQL_TDSCML		VARCHAR(100)	DEFAULT '';
DECLARE strSQL_FECINI		VARCHAR(100)	DEFAULT '';
DECLARE strSQL_FECFIN		VARCHAR(100)	DEFAULT '';
DECLARE strSQL_STPODP		VARCHAR(100)	DEFAULT '';

DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0;
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2;

IF IN_REGPAG <= 0 THEN 
	SET IN_REGPAG = 1;
END IF;

-- Filtros según Nro de Operación
IF IN_NOPRCN <> '' THEN
	IF POSSTR( IN_NOPRCN, ',') <> 0 THEN
		SET IN_NOPRCN = REPLACE( IN_NOPRCN, ' ', '');
		SET strSQL_NOPRCN = ' And RZSC30.NOPRCN IN  ( '  || IN_NOPRCN || ') ' ;
	ELSE
		IF POSSTR( IN_NOPRCN, '*') <> 0 THEN
			SET IN_NOPRCN = REPLACE( IN_NOPRCN, '*', '%');
			SET strSQL_NOPRCN = ' And Trim(RZSC30.NOPRCN) LIKE '''  || IN_NOPRCN || ''' ' ;
		ELSE
			SET strSQL_NOPRCN = ' And RZSC30.NOPRCN = '  || IN_NOPRCN || ' ' ;
		END IF;
	END IF;
END IF;

-- Filtros según el Servicio Seleccionado
IF IN_CSRVNV <> '' THEN
	IF POSSTR( IN_CSRVNV, ',') <> 0 THEN
		SET IN_CSRVNV = REPLACE(REPLACE( IN_CSRVNV, ' ', ''), ',', ''',''');
		SET strSQL_CSRVNV = ' t3.CSRVNV IN  ( '''  || IN_CSRVNV || ''') ' ;
	ELSE
		IF POSSTR( IN_CSRVNV, '*') <> 0 THEN
			SET IN_CSRVNV = REPLACE( IN_CSRVNV, '*', '%');
			SET strSQL_CSRVNV = ' t3.CSRVNV LIKE '''  || IN_CSRVNV || ''' ' ;
		ELSE
			SET strSQL_CSRVNV = ' t3.CSRVNV = '''  || IN_CSRVNV || ''' ' ;
		END IF;
	END IF;
	SET strSQL_CSRVNV = ' And	EXISTS(	SELECT t1.NRSRRB FROM RZSC04 t1 WHERE t1.NRTFSV = RZSC30.NRTFSV
										AND EXISTS( SELECT  t2.NOMSER FROM RZSC08 t2 WHERE t2.NRSRRB = t1.NRSRRB
													AND ' || strSQL_CSRVNV || ' ) ) ';
END IF;

-- Filtros según Fecha de creación de la Orden de Compra mayor o igual
IF IN_FECINI > 0 THEN
	SET strSQL_FECINI = ' And RZSC30.FOPRCN >= ' || IN_FECINI ;
END IF;
-- Filtros según Fecha de creación de la Orden de Compra menor o igual
IF IN_FECFIN > 0  THEN
	SET strSQL_FECFIN = ' And RZSC30.FOPRCN <= ' || IN_FECFIN ;
END IF;

-- Filtros según Fecha de creación de la Orden de Compra menor o igual
IF IN_STPODP <> ''  THEN
	SET strSQL_STPODP = ' And RZSC30.STPODP = ''' || IN_STPODP || ''' ';
END IF;

SET strSQL = 'SELECT Count(NOPRCN) FROM RZSC30 WHERE CCLNT = ? And NOPRCN >= ? ' || strSQL_NOPRCN || ' And CCMPN = ? And CDVSN = ? And SESTRG <> ''*'' ' || 
			  strSQL_FECINI || strSQL_FECFIN || strSQL_CSRVNV || strSQL_STPODP;	

-- Preparamos el Macros que contiene la consulta de toda la información.
PREPARE S0 FROM strSQL;
OPEN CU_00 USING IN_CCLNT, WK_NOPRCN, IN_CCMPN, IN_CDVSN;
FETCH LAST FROM CU_00 INTO WK_TOTPAG;
CLOSE CU_00;

IF MOD(WK_TOTPAG, IN_REGPAG) > 0 THEN
	SET WK_TOTPAG = INTEGER ( WK_TOTPAG / IN_REGPAG ) + 1;
ELSE
	SET WK_TOTPAG = INTEGER ( WK_TOTPAG / IN_REGPAG );
END IF;

IF WK_TOTPAG = 0 THEN
	SET WK_TOTPAG = 1;
END IF;

IF IN_NROPAG > WK_TOTPAG THEN
	SET IN_NROPAG = WK_TOTPAG;
END IF;

SET OU_TOTPAG = WK_TOTPAG;
		  
SET strSQL = 'SELECT NOPRCN FROM RZSC30 WHERE CCLNT = ? And NOPRCN >= ? ' || strSQL_NOPRCN || ' And CCMPN = ? And CDVSN = ? And SESTRG <> ''*'' ' || 
			  strSQL_FECINI || strSQL_FECFIN  || strSQL_CSRVNV || strSQL_STPODP || ' ORDER BY NOPRCN ASC FETCH FIRST ' || (IN_REGPAG + 1) || ' ROWS ONLY ';	
-- Preparamos el Macros que contiene la consulta de toda la información.
PREPARE S1 FROM strSQL;
-- Recorremos todas las páginas anteriores para obtener la última Orden de Compra
WHILE WK_CNTREG < (IN_NROPAG - 1) DO
	OPEN CU_01 USING IN_CCLNT, WK_NOPRCN, IN_CCMPN, IN_CDVSN;
	FETCH LAST FROM CU_01 INTO WK_NOPRCN;
	CLOSE CU_01;
	-- AVANZAMOS EL CONTADOR DE PAGINAS
	SET WK_CNTREG = WK_CNTREG + 1;
END WHILE;

-- Armamos la consulta final con toda la información
SET strSQL = '	SELECT	NOPRCN, NRTFSV, TarifaServicioPorDivision(CCMPN, CDVSN, CCLNT, FOPRCN, NRTFSV) NOMSER,
						NumberToDate(FOPRCN) FOPRCN, CCMPN, CDVSN, QCNESP, TUNDIT, STIPPR, CCLNFC,(	SELECT	t4.TCMPCL FROM RZZM01 t4 
																									WHERE	t4.CCLNT = RZSC30.CCLNFC) TCMPFC,
						QATNAN, CPRCN1, NSRCN1, NumberToDate(FECINI) FECINI, NumberToDate(FECFIN) FECFIN, SESTRG
				FROM	RZSC30
				WHERE	CCLNT = ? And NOPRCN >= ? ' || strSQL_NOPRCN || ' And CCMPN = ? And CDVSN = ? And SESTRG <> ''*'' ' || 
				strSQL_FECINI || strSQL_FECFIN || strSQL_CSRVNV || strSQL_STPODP || ' ORDER BY NOPRCN ASC FETCH FIRST ' || IN_REGPAG || ' ROWS ONLY ';
				
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S2 FROM strSQL;
OPEN CU_02 USING IN_CCLNT, WK_NOPRCN, IN_CCMPN, IN_CDVSN;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_SERVICIOS_RZSC30_L01 TO PUBLIC