-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SA_SERVICIOS_RZSC30_DEL
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SA_SERVICIOS_RZSC30_DEL(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NOPRCN		NUMERIC(10, 0),
		IN	IN_NRTFSV		NUMERIC(12, 0),
		IN  IN_USUARI  		VARCHAR(10),
		OUT OU_DELALL		VARCHAR(1),		-- << S >> Si se borra todo << N >> Si aún existe servicios
		OUT	OU_MSGERR		VARCHAR(200)	-- Mensaje de Error
        )
RESULT SETS 0
LANGUAGE SQL
BEGIN ATOMIC
	--------------------------------------
	-- Variables de Trabajo - Seguridad --
	--------------------------------------
	DECLARE	WK_FECHA	NUMERIC(10, 0)	DEFAULT 0;
	DECLARE	WK_HORA		NUMERIC(10, 0)	DEFAULT 0;
	--------------------------
	-- Variables de Trabajo --
	--------------------------
	DECLARE WK_NRCTSL	NUMERIC(10, 0)	DEFAULT 0;
	DECLARE WK_NRITEM	NUMERIC(6, 0)	DEFAULT 0;
	DECLARE WK_FLGFAC	VARCHAR(1)		DEFAULT '';
	DECLARE WK_SESTRG	VARCHAR(1)		DEFAULT '';
	
	-- Obtengo la fecha y hora actual
	SET	WK_FECHA = YEAR(CURRENT DATE) * 10000 + MONTH(CURRENT DATE) * 100 + DAY(CURRENT DATE);
	SET	WK_HORA  = HOUR(CURRENT TIME) * 10000 + MINUTE(CURRENT TIME) * 100 + SECOND(CURRENT TIME);
	SET OU_DELALL = 'N';
	SET OU_MSGERR = '';
	
	IF EXISTS( SELECT NRTFSV FROM RZSC30 WHERE CCLNT = IN_CCLNT AND NOPRCN = IN_NOPRCN AND NRTFSV = IN_NRTFSV AND SESTRG <> '*' ) THEN
		-- Obtengo los campos relacionados al Status del detalle del contrato
		SELECT	FLGFAC, SESTRG
		INTO	WK_FLGFAC, WK_SESTRG
		FROM	RZSC02
		WHERE	CCLNT  = IN_CCLNT 
		AND		NOPRCN = IN_NOPRCN
		AND		NRTFSV = IN_NRTFSV;
		
		IF WK_FLGFAC = 'S' THEN
			SET OU_MSGERR = 'Servicio ya se encuentra Facturado.';
		ELSE
			UPDATE	RZSC30
			SET		SESTRG = '*',
					CULUSA = IN_USUARI,
					FULTAC = WK_FECHA,
					HULTAC = WK_HORA,
					UPDATE_IDENT = UPDATE_IDENT + 1
			WHERE	CCLNT  = IN_CCLNT 
			AND		NOPRCN = IN_NOPRCN 
			AND		NRTFSV = IN_NRTFSV;
			
			IF WK_SESTRG <> '*' THEN
				UPDATE	RZSC02 
				SET		SESTRG = '*',
						CULUSA = IN_USUARI,
						FULTAC = WK_FECHA,
						HULTAC = WK_HORA,
						UPDATE_IDENT = UPDATE_IDENT + 1
				WHERE	CCLNT  = IN_CCLNT 
				AND		NOPRCN = IN_NOPRCN 
				AND		NRTFSV = IN_NRTFSV;
			END IF;
			
			IF NOT EXISTS( SELECT NRTFSV FROM RZSC30 WHERE CCLNT = IN_CCLNT AND NOPRCN = IN_NOPRCN AND SESTRG <> '*' ) THEN
				UPDATE	RZSC31
				SET		SESTRG = '*',
						CULUSA = IN_USUARI,
						FULTAC = WK_FECHA,
						HULTAC = WK_HORA,
						UPDATE_IDENT = UPDATE_IDENT + 1
				WHERE	CCLNT  = IN_CCLNT 
				AND		NOPRCN = IN_NOPRCN;
			
				SET OU_DELALL = 'S';
			END IF;
		END IF;
	ELSE
		SET OU_MSGERR = 'El Servicio ya fue eliminado.';
	END IF;
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_SERVICIOS_RZSC30_DEL TO PUBLIC