DROP PROCEDURE SP_SOLMIN_SA_SERVICIOS_DETALLE_RZSC31_L01
GO
CREATE PROCEDURE SP_SOLMIN_SA_SERVICIOS_DETALLE_RZSC31_L01(
       IN  IN_CCLNT        NUMERIC(6, 0),
       IN  IN_NOPRCN       NUMERIC(10,0),
       IN  IN_CCMPN        VARCHAR(2),
       IN  IN_CDVSN        VARCHAR(1),
       IN  IN_CPLNDV       NUMERIC(3)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN
DECLARE strSQL  VARCHAR(6000)   DEFAULT '';

DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2;

-- Creamos la tabla temporal que contiene los datos del Reporte
Declare Global Temporary Table SESSION.tmpBultos(
CREFFW          VARCHAR(20),    DESCWB          VARCHAR(40),    TUBRFR          VARCHAR(17),    QREFFW          NUMERIC(7, 0),
TIPBTO          VARCHAR(10),    QPSOBL          DECIMAL(15, 5), TUNPSO          VARCHAR(10),    QVLBTO          NUMERIC(15, 5),
TUNVOL          VARCHAR(10),    QAROCP          NUMERIC(6, 2),  SESTRG          VARCHAR(1) ) WITH REPLACE Not Logged;

FOR_LOOP:
FOR FILA AS CU_01 CURSOR FOR
SELECT  CREFFW
FROM    RZSC31
WHERE   CCLNT  = IN_CCLNT
And     NOPRCN = IN_NOPRCN
And     SESTRG <> '*'
ORDER BY CREFFW
DO
        Insert Into SESSION.tmpBultos(CREFFW, DESCWB, TUBRFR, QREFFW, TIPBTO, QPSOBL, TUNPSO, QVLBTO, TUNVOL, QAROCP, SESTRG)
        select  RZ65.CREFFW, RZ65.DESCWB, RZ65.TUBRFR, RZ65.QREFFW, RZ65.TIPBTO, RZ65.QPSOBL, RZ65.TUNPSO, RZ65.QVLBTO, RZ65.TUNVOL, RZ65.QAROCP, RZ65.SESTRG
        From    RZOL65 RZ65
        Where   RZ65.CCLNT  = IN_CCLNT
        And     RZ65.CREFFW = FILA.CREFFW
        And     RZ65.CCMPN =IN_CCMPN
        And     RZ65.CDVSN =IN_CDVSN
        And     RZ65.CPLNDV =IN_CPLNDV;

END FOR;

SET strSQL = '  select  CREFFW, DESCWB, TUBRFR, QREFFW, TIPBTO, QPSOBL, TUNPSO, QVLBTO, TUNVOL, QAROCP, SESTRG
                                From    SESSION.tmpBultos';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S2 FROM strSQL;
OPEN CU_02;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_SERVICIOS_DETALLE_RZSC31_L01 TO PUBLIC