-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC32_L01
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC32_L01(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_CCMPN		VARCHAR(2),
		IN	IN_CDVSN		VARCHAR(1),
		IN	IN_CPLNDV		NUMERIC(3, 0),
		IN	IN_STPODP		VARCHAR(1),
		IN	IN_NPRALM		NUMERIC(10, 0),
		IN	IN_NANPRC		NUMERIC(4, 0),
		IN	IN_NMES			NUMERIC(2, 0)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE		strSQL			VARCHAR(1000);

DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0;

-- Armamos la consulta final con toda la información
SET strSQL =  '	SELECT	NPRALM, CCMPN, CDVSN, CPLNDV, STPODP, NANPRC, NMES, NumberToDate(FECINI) FECINI, NumberToDate(FECFIN) FECFIN, ' || 
					'	OBSERV, NDIALI, STPOFC, TQAROC, TQPSOB, TQVLBT, TNDPER, TNDAFA, NOPRCN, NRTFSV, QCNESP, TUNDIT, STPOUN, ' || 
					'	CMNDA1, NMONOC, VALUNI, IMPFACT, SESTRG ' ||
			  '	FROM	RZSC32 ' || 
			  '	WHERE	CCLNT	= ? ' || 
			  ' AND		CCMPN	= ? ' ||
			  ' AND		CDVSN	= ? ' ||
			  ' AND		CPLNDV	= ? ' ||
			  ' AND		STPODP	= ? ' ||
			  '	AND	( ( ' || IN_NPRALM || ' = 0 ) OR ( ' || IN_NPRALM || ' <> 0  AND NPRALM	= ' || IN_NPRALM || ' ) ) ' ||
			  '	AND	( ( ' || IN_NANPRC || ' = 0 ) OR ( ' || IN_NANPRC || ' <> 0  AND NANPRC	= ' || IN_NANPRC || ' ) ) ' ||
			  '	AND	( ( ' || IN_NMES || ' = 0 ) OR ( ' || IN_NMES || ' <> 0  AND NMES = ' || IN_NMES || ' ) ) ' ||
			  '	AND		SESTRG <> ''*'' ' || 
			  ' ORDER BY NPRALM DESC ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S0 FROM strSQL;
OPEN CU_00 USING IN_CCLNT, IN_CCMPN, IN_CDVSN, IN_CPLNDV, IN_STPODP;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_ALMACENAJE_RZSC32_L01 TO PUBLIC