-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC32_R01
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC32_R01(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NPRALM		NUMERIC(10, 0)
        )
RESULT SETS 2
LANGUAGE SQL
BEGIN 
DECLARE		strSQL			VARCHAR(1000);

DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0;
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;

-- Armamos la consulta final con toda la información
SET strSQL =  '	SELECT	t1.NPRALM, t1.CCLNT, t3.TCMPCL, t3.TDRCOR, t3.NRUC, t1.CCMPN, t1.CDVSN, t1.CPLNDV, t1.STPODP, t1.NANPRC, t1.NMES, ' || 
					'	NumberToDate(t1.FECINI) FECINI, NumberToDate(t1.FECFIN) FECFIN, t1.OBSERV, t1.NDIALI, t1.STPOFC, t1.TQAROC, t1.TQPSOB, t1.TQVLBT, ' || 
					'	t1.TNDPER, t1.TNDAFA, t1.NOPRCN, t1.NRTFSV, t1.QCNESP, t1.TUNDIT, t1.STPOUN, t1.CMNDA1, t1.NMONOC, t1.VALUNI, t1.IMPFACT, t1.SESTRG ' ||
			  '	FROM	RZSC32 t1 INNER JOIN ' || 
					' (	SELECT	t2.CCLNT, t2.TCMPCL, t2.TDRCOR, t2.NRUC ' ||
					'	FROM	RZZM01 t2 ' ||
					'	WHERE	t2.CCLNT = ? ) t3 ON t1.CCLNT = t3.CCLNT ' ||
			  '	WHERE	t1.CCLNT	= ? ' || 
			  '	AND		t1.NPRALM	= ? ' || 
			  '	AND		t1.SESTRG <> ''*'' ' || 
			  ' ORDER BY t1.NPRALM DESC ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S0 FROM strSQL;
OPEN CU_00 USING IN_CCLNT, IN_CCLNT, IN_NPRALM;

-- Armamos la consulta final con toda la información
SET strSQL =  '	SELECT	t1.NPRALM, t1.CREFFW, (SELECT t2.TUBRFR FROM RZOL65 t2 WHERE t2.CCLNT = t1.CCLNT AND t2.CREFFW = t1.CREFFW ) TUBRFR, ' ||
					  ' NumberToDate(t1.FREFFW) FREFFW, NumberToDate(t1.FULFAC) FULFAC, ' || 
					  ' NumberToDate(t1.FECINI) FECINI, NumberToDate(t1.FECFIN) FECFIN, t1.QAROCP, t1.QPSOBL, t1.QVLBTO, t1.NDPERM, ' || 
					  ' t1.NDLIAC, t1.NDLIPE, t1.NDFACT, t1.NDAFAC, t1.IMPFACT, t1.SESTRG ' || 
			  ' FROM	RZSC33 t1' || 
			  '	WHERE	t1.CCLNT	= ? ' ||
			  '	AND		t1.NPRALM	= ? ' ||
			  '	AND		t1.SESTRG <> ''*'' ' || 
			  ' ORDER BY t1.CREFFW ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S1 FROM strSQL;
OPEN CU_01 USING IN_CCLNT, IN_NPRALM;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_ALMACENAJE_RZSC32_R01 TO PUBLIC