-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC33_DEL
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC33_DEL(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NPRALM		NUMERIC(10, 0),
		IN	IN_CREFFW		VARCHAR(20),
        IN  IN_USUARI  		VARCHAR(10),
		OUT OU_MSGERR		VARCHAR(200)	-- Mensaje de Error
        )
RESULT SETS 0
LANGUAGE SQL
BEGIN ATOMIC
	--------------------------------------
	-- Variables de Trabajo - Seguridad --
	--------------------------------------
	DECLARE	WK_FECHA	NUMERIC(10, 0)	DEFAULT 0;
	DECLARE	WK_HORA		NUMERIC(10, 0)	DEFAULT 0;
	--------------------------
	-- Variables de Trabajo --
	--------------------------
	DECLARE WK_QAROCP			DECIMAL(15, 5)	DEFAULT 0;
	DECLARE WK_QPSOBL			DECIMAL(15, 5)	DEFAULT 0;
	DECLARE WK_QVLBTO			DECIMAL(15, 5)	DEFAULT 0;
	DECLARE WK_NDPERM			DECIMAL(15, 5)	DEFAULT 0;
	DECLARE WK_NDAFAC			DECIMAL(15, 5)	DEFAULT 0;

	-- Obtengo la fecha y hora actual
	SET	WK_FECHA = YEAR(CURRENT DATE) * 10000 + MONTH(CURRENT DATE) * 100 + DAY(CURRENT DATE);
	SET	WK_HORA  = HOUR(CURRENT TIME) * 10000 + MINUTE(CURRENT TIME) * 100 + SECOND(CURRENT TIME);
	SET OU_MSGERR = '';

	IF EXISTS( SELECT NPRALM FROM RZSC32 WHERE NPRALM = IN_NPRALM AND STPOFC = 'P' ) THEN
	
		SELECT	IFNULL(QAROCP, 0), IFNULL(QPSOBL, 0), IFNULL(QVLBTO,0), IFNULL(NDPERM,0), IFNULL(NDAFAC,0)
		INTO	WK_QAROCP, WK_QPSOBL, WK_QVLBTO, WK_NDPERM, WK_NDAFAC
		FROM	RZSC33
		Where	NPRALM = IN_NPRALM
		AND		CCLNT  = IN_CCLNT
		AND		CREFFW = IN_CREFFW;
		
		Update	RZSC32
		Set		TQAROC = TQAROC - WK_QAROCP,
				TQPSOB = TQPSOB - WK_QPSOBL,
				TQVLBT = TQVLBT - WK_QVLBTO, 
				TNDPER = TNDPER - WK_NDPERM, 
				TNDAFA = TNDAFA - WK_NDAFAC,
				CULUSA = IN_USUARI,
				FULTAC = WK_FECHA,
				HULTAC = WK_HORA,
				UPDATE_IDENT = UPDATE_IDENT + 1
		Where	NPRALM = IN_NPRALM
		and		CCLNT  = IN_CCLNT;
		
		Delete From RZSC33
		Where	NPRALM = IN_NPRALM
		AND		CCLNT  = IN_CCLNT
		AND		CREFFW = IN_CREFFW;
	ELSE
		SET OU_MSGERR = 'Información no puede ser Eliminada.';
	END IF;
END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_ALMACENAJE_RZSC33_DEL TO PUBLIC