-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC33_L01
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_SA_ALMACENAJE_RZSC33_L01(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NPRALM		NUMERIC(10, 0),	-- Nro. Operación.
		IN  IN_USUARI  		VARCHAR(10)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE		strSQL			VARCHAR(1000);

DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0;

-- Armamos la consulta final con toda la información
SET strSQL =  '	SELECT	CCLNT, NPRALM, CREFFW, NumberToDate(FREFFW) FREFFW, NumberToDate(FULFAC) FULFAC, ' || 
					  ' NumberToDate(FECINI) FECINI, NumberToDate(FECFIN) FECFIN, QAROCP, QPSOBL, QVLBTO, NDPERM, ' || 
					  ' NDLIAC, NDLIPE, NDFACT, NDAFAC, IMPFACT, SESTRG ' || 
			  ' FROM	RZSC33 ' || 
			  '	WHERE	CCLNT	= ' || IN_CCLNT || 
			  '	AND	( ( ' || IN_NPRALM || ' = 0 ) OR ( ' || IN_NPRALM || ' <> 0  AND NPRALM	= ' || IN_NPRALM || ' ) ) ' ||
			  '	AND		SESTRG <> ''*'' ' || 
			  ' ORDER BY CREFFW ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S0 FROM strSQL;
OPEN CU_00;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_ALMACENAJE_RZSC33_L01 TO PUBLIC