-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_ITEMS_X_OC_Q01
GO
CREATE PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_ITEMS_X_OC_Q01(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NORCML		VARCHAR(35)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN
DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2;


-- Armamos la consulta final con toda la información
SET strSQL = '	SELECT	NRITOC, QCNTIT, QCNRCP, QCNDPC, QSTKIT
				FROM	RZOL39
				WHERE	NORCML = ? And CCLNT = ? AND SESTRG <> ''*'' 
				ORDER BY NRITOC ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S2 FROM strSQL;
OPEN CU_02 USING IN_NORCML, IN_CCLNT;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_YRC_ITEMS_X_OC_Q01 TO PUBLIC
