-- CAMBIAR RNSLIB POR RNSLIB
DROP PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_M004_CHECKPOINT_Q01
GO
CREATE PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_M004_CHECKPOINT_Q01
RESULT SETS 1 
LANGUAGE SQL 
BEGIN ATOMIC 
	---------------------------------------
	-- Variables de Trabajo - Seguridad  -- 
	---------------------------------------
	DECLARE	WK_FECHA	NUMERIC (10 , 0)		DEFAULT 0; 
	DECLARE	WK_HORA		NUMERIC (10 , 0)		DEFAULT 0; 
	 ---------------------------
	 -- Variables de Trabajo  -- 
	 ---------------------------
	DECLARE WK_CCLNT 		NUMERIC(6, 0)	DEFAULT 0; 
	DECLARE WK_SIDYRC		VARCHAR(22)		DEFAULT ''; 
	DECLARE WK_STRSQL		VARCHAR(1000)	DEFAULT '';
	 
	-- Cursor para mostrar el resultado 
	DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2 ; 
	-- Creamos la tabla temporal que contiene los datos del Reporte 
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.M004_CHECKPOINT ( 
	CCODCP		VARCHAR(6),	SNOMCP		VARCHAR(250),	CTIPSEG	INTEGER,	CUSUCRE		VARCHAR(20),
	DFECCRE		DATE,		CUSUACT		VARCHAR(20),	DFECACT		DATE,	FACTIVO		VARCHAR(1) ) WITH REPLACE NOT LOGGED ; 
	
	-- Obtengo la fecha y hora actual 
	SET	WK_FECHA = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
	SET	WK_HORA = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ; 
  
	FOR_LOOP:
	FOR FILA AS CU_01 CURSOR FOR
	SELECT	'RNS' || RIGHT(DIGITS(NESTDO),3) NESTDO, TRIM(TDESES) TDESES
	FROM	RZOL51
	WHERE	SESTRG <> '*'
	ORDER BY 1
	DO
		INSERT INTO SESSION.M004_CHECKPOINT( CCODCP, SNOMCP, CTIPSEG, FACTIVO, CUSUCRE, CUSUACT )
		VALUES(FILA.NESTDO, FILA.TDESES, '1', '1', 0, 0 );
	END FOR;
  
	SET WK_STRSQL = 'Select	* From SESSION.M004_CHECKPOINT Order By 1' ;	 
	-- Realizamos la preparación de la Consulta para ser ejecutada 
	PREPARE S2 FROM WK_STRSQL ; 
	OPEN CU_02 ; 
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_YRC_M004_CHECKPOINT_Q01 TO PUBLIC