-- CAMBIAR RNSLIB POR RNSLIB
DROP PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_T006_SUSTENTO_COSTO
GO
CREATE PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_T006_SUSTENTO_COSTO( 
	IN	IN_NORSCI	NUMERIC(10, 0) 
) 
RESULT SETS 2
LANGUAGE SQL 
BEGIN ATOMIC 
	---------------------------------------
	-- Variables de Trabajo - Seguridad  -- 
	---------------------------------------
	DECLARE	WK_FECHA	NUMERIC (10 , 0)		DEFAULT 0; 
	DECLARE	WK_HORA		NUMERIC (10 , 0)		DEFAULT 0; 
	 ---------------------------
	 -- Variables de Trabajo  -- 
	 ---------------------------
	DECLARE WK_STRSQL	VARCHAR(4000)			DEFAULT '';
	 
	-- Cursor para mostrar el resultado 
	DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1 ; 
	DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2 ; 
	
	-- Creamos la tabla temporal que contiene los datos del Reporte 
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.T011_SUSTENTO( 
	CIDSUST		INTEGER,		NYRCRNS		VARCHAR(3),		CTIPDOC		INTEGER,		SRUTA		VARCHAR(800),
	CUSUCRE		VARCHAR(20),	DFECCRE		DATE,			CUSUACT		VARCHAR(20),	DFECACT		DATE ) WITH REPLACE NOT LOGGED ; 
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.T006_COSTO_SUSTENTO( 
	SNROOC		VARCHAR(20),	SNROITE		VARCHAR(15),	CCODCOS		VARCHAR(6),		SIDYRC		VARCHAR(22),
	SREF		VARCHAR(20),	CIDSUST		INTEGER,		NVALORI		NUMERIC(18,6),	NVALOC		NUMERIC(18,6),
	CMONORI		VARCHAR(3),		NVALEST		NUMERIC(18,6),	CMONEST		VARCHAR(3),		CIDDOC		INTEGER,
	CUSUCRE		VARCHAR(20),	DFECCRE		DATE,			CUSUACT		VARCHAR(20),	DFECACT		DATE,
	NYRCRNS		VARCHAR(3),		NORDEN		INTEGER ) WITH REPLACE NOT LOGGED ; 
	
	-- Obtengo la fecha y hora actual 
	SET	WK_FECHA = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
	SET	WK_HORA = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ; 
	
	-- Armamos la consulta final con toda la información
	SET WK_STRSQL = '	DECLARE Global Temporary Table SustentoPorEmbarque AS ( ' ||
					'	SELECT	SEGCAR.NOREMB, DETCAR.NORCML, DETCAR.NRITEM, DETOC.IVLORG, DETOC.IVLDOL, DETOC.CMNDA1, RIGHT(''000'' || LISVAR.NRVARB, 3) NRVARB, ' ||
							'	DETCAR.NRPEMB, ( SELECT TRIM( DOCUM.URLARC) CONCAT '''' CONCAT  DOCUM.TNMBAR ' ||
											  '  FROM	RZOL42D REDOEM, ' ||
													  ' RZOL53C DOCUM ' ||
											  '	 WHERE  REDOEM.NORSCI = SEGCAR.NORSCI ' ||
											  '	 AND    REDOEM.CODVAR = DETOC.CODVAR ' ||
											  '	 AND    DOCUM.NDOCIN  = REDOEM.NDOCIN ' ||
											  '  AND    DOCUM.NORSCI  = SEGCAR.NORSCI )RUTA ' ||
					'	FROM	RZOL41 SEGCAR, ' ||
							'	RZOL40 DETCAR, ' ||
							'	RZOL40C DETOC, ' ||
							'	RZOL31Z LISVAR ' ||
					'	WHERE	SEGCAR.NORSCI = ' || IN_NORSCI  ||
					'	AND		DETCAR.NORSCI = SEGCAR.NORSCI ' ||
					'	AND		DETOC.NORSCI  = DETCAR.NORSCI ' ||
					'	AND		DETOC.CCLNT   = DETCAR.CCLNT  ' ||
					'	AND		DETOC.NORCML  = DETCAR.NORCML ' ||
					'	AND		DETOC.NRITEM  = DETCAR.NRITEM ' ||
					'	AND		DETOC.NRPEMB  = DETCAR.NRPEMB ' ||
					'	AND		LISVAR.VALVAR = DETOC.CODVAR  ' ||
					'	AND		LISVAR.FLGENV = ''S'' ' ||
					'	AND		LISVAR.SESTRG <> ''*'' ' ||
					'	AND		SEGCAR.SESTRG <> ''*'' ' ||
					'	AND		DETCAR.SESTRG <> ''*'' ' ||
					' )WITH DATA WITH REPLACE Not Logged ' ;

	PREPARE dclstmt FROM WK_STRSQL;
	EXECUTE dclstmt;
	
	INSERT INTO SESSION.T011_SUSTENTO( CIDSUST,	NYRCRNS, CTIPDOC, SRUTA, CUSUCRE, CUSUACT )
	SELECT	DISTINCT Trim(NRPEMB), 'RNS', 2, Trim(RUTA), 485, 485
	FROM	Session.SustentoPorEmbarque
	Where	IFNULL(RUTA, '') <> '';
	
	INSERT INTO SESSION.T006_COSTO_SUSTENTO(SNROOC,		SNROITE,	CCODCOS,	SIDYRC,		SREF,		CIDSUST,
											NVALORI,	NVALOC,		CMONORI,	NVALEST,	CMONEST,	CIDDOC,
											NYRCRNS,	NORDEN,		CUSUCRE,	CUSUACT )
	SELECT	DISTINCT Trim(NORCML), NRITEM, 'RNS' || NRVARB, NOREMB, '', NRPEMB, IVLORG, IVLORG, 'USD', IVLORG, 
			'USD', 100, 'RNS', 1, 485, 485
	FROM	Session.SustentoPorEmbarque
	Where	IFNULL(RUTA, '') <> '';
	
	INSERT INTO SESSION.T006_COSTO_SUSTENTO(SNROOC,		SNROITE,	CCODCOS,	SIDYRC,		SREF,		CIDSUST,
											NVALORI,	NVALOC,		CMONORI,	NVALEST,	CMONEST,	CIDDOC,
											NYRCRNS,	NORDEN,		CUSUCRE,	CUSUACT )
	SELECT	DISTINCT Trim(NORCML), NRITEM, 'RNS' || NRVARB, NOREMB, '', 0, IVLORG, IVLORG, 'USD', IVLORG, 
			'USD', 100, 'RNS', 1, 485, 485
	FROM	Session.SustentoPorEmbarque
	Where	IFNULL(RUTA, '') = '';
	
  
	SET WK_STRSQL = 'Select	* From SESSION.T011_SUSTENTO Order By 1' ;	 
	-- Realizamos la preparación de la Consulta para ser ejecutada 
	PREPARE S1 FROM WK_STRSQL ; 
	OPEN CU_01 ; 
	
	SET WK_STRSQL = 'Select	* From SESSION.T006_COSTO_SUSTENTO Order By 1, 2, 3' ;	 
	-- Realizamos la preparación de la Consulta para ser ejecutada 
	PREPARE S2 FROM WK_STRSQL ; 
	OPEN CU_02 ; 
	
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_YRC_T006_SUSTENTO_COSTO TO PUBLIC