-- CAMBIAR RNSLIB POR RNSLIB
DROP PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_ITEM_OC_Q01
GO
CREATE PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_ITEM_OC_Q01( 
	IN	IN_NORSCI	NUMERIC(10, 0) 
) 
RESULT SETS 1 
LANGUAGE SQL 
BEGIN ATOMIC 
	---------------------------------------
	-- Variables de Trabajo - Seguridad  -- 
	---------------------------------------
	DECLARE	WK_FECHA	NUMERIC (10 , 0)		DEFAULT 0; 
	DECLARE	WK_HORA		NUMERIC (10 , 0)		DEFAULT 0; 
	 ---------------------------
	 -- Variables de Trabajo  -- 
	 ---------------------------
	DECLARE WK_CCLNT 		NUMERIC(6, 0)	DEFAULT 0; 
	DECLARE WK_CCLNT_YRC	NUMERIC(6, 0)	DEFAULT 0; 
	DECLARE WK_SIDYRC		VARCHAR(22)		DEFAULT ''; 
	DECLARE WK_NNROPAR		INTEGER			DEFAULT 0;
	DECLARE WK_QRLCSC		DECIMAL(15, 5)	DEFAULT 0;
	DECLARE WK_TUNDIT		VARCHAR(3)		DEFAULT '';
	DECLARE WK_STRSQL		VARCHAR(1000)	DEFAULT '';
	 
	-- Cursor para mostrar el resultado 
	DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2 ; 
	-- Creamos la tabla temporal que contiene los datos del Reporte 
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.T007_ITEM_OC ( 
	CCLIENT		INTEGER,		SNROOC		VARCHAR(20),		SNROITE		VARCHAR(15),		NNROPAR		INTEGER,
	SIDYRC		VARCHAR(22),	NVOLUM		NUMERIC(18,6),		NPESO		NUMERIC(18,6),		NCANT		NUMERIC(18,6),
	SWAYBIL		VARCHAR(20),	DING		DATE,				CUNDPES		VARCHAR(3),			CUNDVOL		VARCHAR(3),
	DSALIDA		DATE,			CUNDMED		VARCHAR(3),			NLCYRC		NUMERIC(18,6),		NLCRNS		NUMERIC(18,6),
	CUSUCRE		VARCHAR(20),	DFECCRE		DATE,				CUSUACT		VARCHAR(20),		DFECACT		DATE ) WITH REPLACE NOT LOGGED ;

	-- Obtengo la fecha y hora actual 
	SET	WK_FECHA = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
	SET	WK_HORA = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ; 
  
	SELECT	T0.CCLNT, Trim(T0.NOREMB)
	INTO	WK_CCLNT, WK_SIDYRC
	FROM	RZOL41 T0 
	WHERE	T0.NORSCI = IN_NORSCI;
	
	IF WK_CCLNT = 2287 THEN
		SET WK_CCLNT_YRC = 29;
	ELSE
	    IF WK_CCLNT = 48916 THEN
			SET WK_CCLNT_YRC = 370;
		ELSE
		    IF WK_CCLNT = 46550 THEN
				SET WK_CCLNT_YRC = 371;
			ELSE
			    IF WK_CCLNT = 48623 THEN
					SET WK_CCLNT_YRC = 372;
				ELSE
				    IF WK_CCLNT = 48622 THEN
						SET WK_CCLNT_YRC = 373;
					END IF;
				END IF;
			END IF;
		END IF;
	END IF;
	
	FOR_LOOP:
	FOR FILA AS CU_01 CURSOR FOR
	SELECT  Trim(RZOL40.NORCML) NORCML, RZOL40.NRITEM, RZOL40.NRPEMB
	FROM    RZOL40
	WHERE   RZOL40.NORSCI = IN_NORSCI
	AND     RZOL40.SESTRG <> '*'
	DO
		SET WK_NNROPAR = 1;
		
		IF FILA.NRPEMB <> '' THEN
			SELECT	RZOL39P.NRPARC, RZOL39P.QRLCSC
			INTO	WK_NNROPAR, WK_QRLCSC
			FROM	RZOL39P 
			WHERE	RZOL39P.NRPEMB = FILA.NRPEMB
			AND		RZOL39P.CCLNT = WK_CCLNT;
			
			SELECT	Trim( RZOL39.TUNDIT )
			INTO	WK_TUNDIT
			FROM	RZOL39 
			WHERE	RZOL39.CCLNT = WK_CCLNT
			AND		RZOL39.NORCML = FILA.NORCML
			AND		RZOL39.NRITOC = FILA.NRITEM;
		END IF;
		
		INSERT INTO SESSION.T007_ITEM_OC ( CCLIENT,	SNROOC,	SNROITE, NNROPAR, SIDYRC, NVOLUM, NPESO, NCANT, CUNDPES, CUNDVOL, CUNDMED, NLCYRC, NLCRNS, CUSUCRE, CUSUACT )
		VALUES(WK_CCLNT_YRC, FILA.NORCML, FILA.NRITEM, WK_NNROPAR, WK_SIDYRC, 0, 0, WK_QRLCSC, 'KGS', 'CM', WK_TUNDIT, 0, 0, 0, 0 );
	END FOR;
	
	SET WK_STRSQL = 'Select	* From SESSION.T007_ITEM_OC Order By 1, 2, 3, 4 ';
	-- Realizamos la preparación de la Consulta para ser ejecutada 
	PREPARE S2 FROM WK_STRSQL ; 
	OPEN CU_02 ; 
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_YRC_ITEM_OC_Q01 TO PUBLIC