-- CAMBIAR RNSLIB POR RNSLIB
DROP PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_T002_CAMBIAR_STATUS_OC
GO
CREATE PROCEDURE DC@RNSLIB.SP_SOLMIN_SA_YRC_T002_CAMBIAR_STATUS_OC( 
	IN	IN_NORSCI	NUMERIC(10, 0),
	IN	IN_STREGI	VARCHAR(1)
) 
RESULT SETS 1 
LANGUAGE SQL 
BEGIN ATOMIC 
	---------------------------------------
	-- Variables de Trabajo - Seguridad  -- 
	---------------------------------------
	DECLARE	WK_FECHA	NUMERIC (10 , 0)		DEFAULT 0; 
	DECLARE	WK_HORA		NUMERIC (10 , 0)		DEFAULT 0; 
	 ---------------------------
	 -- Variables de Trabajo  -- 
	 ---------------------------
	DECLARE WK_CCLNT 		NUMERIC(6, 0)	DEFAULT 0; 
	DECLARE WK_CCLNT_YRC	NUMERIC(6, 0)	DEFAULT 0; 
	DECLARE WK_SIDYRC		VARCHAR(22)		DEFAULT ''; 
	DECLARE WK_STRSQL		VARCHAR(1000)	DEFAULT '';
	DECLARE WK_NCNTRECALM	NUMERIC(18,6)	DEFAULT 0;
	DECLARE WK_NCNTSTKALM	NUMERIC(18,6)	DEFAULT 0;
	 
	-- Cursor para mostrar el resultado 
	DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2 ; 
	-- Creamos la tabla temporal que contiene los datos del Reporte 
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.T002_ITEM_OC ( 
	CCLIENT		INTEGER,		SNROOC		VARCHAR(20),	SNROITE		VARCHAR(15),	NCNTORD		NUMERIC(18,6),	CUNDMED		VARCHAR(3),
	SNROPTE		VARCHAR(50),	SPREUNI		NUMERIC(18,6),	SDESC		VARCHAR(800),	DREQ		DATE,			SLUGENT		VARCHAR(250),
	SCOMENT		VARCHAR(800),	NCNTRECORI	NUMERIC(18,6),	NCNTSHPORI	NUMERIC(18,6),	NCNTRECDES	NUMERIC(18,6),	NCNTRECALM	NUMERIC(18,6),
	NCNTTRADES	NUMERIC(18,6),	NCNTDEVALM	NUMERIC(18,6),	NCNTSTKALM	NUMERIC(18,6),	CUSUCRE		VARCHAR(20),	DFECCRE		DATE,
	CUSUACT		VARCHAR(20),	DFECACT		DATE,			FDIS		INTEGER,		FPEN		INTEGER,		DESTSUP		DATE,
	DDISEND		DATE,			SMERCLI		VARCHAR(10),	NCNTALMDES	NUMERIC(18,6) ) WITH REPLACE NOT LOGGED ;

	-- Obtengo la fecha y hora actual 
	SET	WK_FECHA = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
	SET	WK_HORA = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ; 
  
	SELECT	T0.CCLNT, Trim(T0.NOREMB)
	INTO	WK_CCLNT, WK_SIDYRC
	FROM	RZOL41 T0 
	WHERE	T0.NORSCI = IN_NORSCI;
	
	IF WK_CCLNT = 2287 THEN
		SET WK_CCLNT_YRC = 29;
	ELSE
	    IF WK_CCLNT = 48916 THEN
			SET WK_CCLNT_YRC = 370;
		ELSE
		    IF WK_CCLNT = 46550 THEN
				SET WK_CCLNT_YRC = 371;
			ELSE
			    IF WK_CCLNT = 48623 THEN
					SET WK_CCLNT_YRC = 372;
				ELSE
				    IF WK_CCLNT = 48622 THEN
						SET WK_CCLNT_YRC = 373;
					END IF;
				END IF;
			END IF;
		END IF;
	END IF;
	
	FOR_LOOP:
	FOR FILA AS CU_01 CURSOR FOR
	SELECT  Trim(RZOL40.NORCML) NORCML, RZOL40.NRITEM, RZOL40.QRLCSC
	FROM    RZOL40
	WHERE   RZOL40.NORSCI = IN_NORSCI
	AND     RZOL40.SESTRG <> '*'
	ORDER BY 1, 2, 3
	DO
		IF IN_STREGI = 'T' THEN
			SET	WK_NCNTRECALM = FILA.QRLCSC;
			SET WK_NCNTSTKALM = 0;
		ELSE
			SET	WK_NCNTRECALM = 0;
			SET WK_NCNTSTKALM = FILA.QRLCSC;
		END IF;
		-- NCNTRECALM
		IF NOT EXISTS( SELECT CCLIENT FROM SESSION.T002_ITEM_OC WHERE CCLIENT = WK_CCLNT_YRC AND SNROOC = FILA.NORCML AND SNROITE = FILA.NRITEM ) THEN
			INSERT INTO SESSION.T002_ITEM_OC ( CCLIENT,	SNROOC,	SNROITE, NCNTRECALM, NCNTSTKALM, CUSUCRE, CUSUACT )
			VALUES(WK_CCLNT_YRC, FILA.NORCML, FILA.NRITEM, WK_NCNTRECALM, WK_NCNTSTKALM, 'RANSA', 'RANSA' );
		ELSE
			UPDATE	SESSION.T002_ITEM_OC
			SET		NCNTRECALM = NCNTRECALM + WK_NCNTRECALM,
					NCNTSTKALM = NCNTSTKALM + WK_NCNTSTKALM
			WHERE	CCLIENT = WK_CCLNT_YRC 
			AND		SNROOC = FILA.NORCML 
			AND		SNROITE = FILA.NRITEM;
		END IF;
		-- FILA.QRLCSC
	END FOR;
	
	SET WK_STRSQL = 'Select	* From SESSION.T002_ITEM_OC Order By 1, 2, 3 ';
	-- Realizamos la preparación de la Consulta para ser ejecutada 
	PREPARE S2 FROM WK_STRSQL ; 
	OPEN CU_02 ; 
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_SA_YRC_T002_CAMBIAR_STATUS_OC TO PUBLIC