-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L03
GO
CREATE PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L03(
		IN	IN_CCLNT		NUMERIC(6, 0)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN
DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2;


-- Armamos la consulta final con toda la información
SET strSQL = '	SELECT	Trim(CCMPRN) CCMPRN,  Trim(TDSDES) TDSDES
				FROM	RZO103
				WHERE	CODVAR = ?
				ORDER BY CCMPRN ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S2 FROM strSQL;
OPEN CU_02 USING IN_CCLNT;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L03 TO PUBLIC