-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE  SP_SOLMIN_OC_ITEM_RZOL39_L02
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_OC_ITEM_RZOL39_L02(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NORCML		VARCHAR(35),
		IN	IN_CPRVCL		NUMERIC(6, 0),
		IN	IN_TTINTC		VARCHAR(6),
		IN	IN_FORCMI		NUMERIC(8, 0),
		IN	IN_FORCMF		NUMERIC(8, 0),
		IN	IN_FMPDMI		NUMERIC(8, 0),
		IN	IN_FMPDMF		NUMERIC(8, 0),
		IN	IN_STATOC		VARCHAR(1)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN
DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE WK_CCLNT			VARCHAR(100)	DEFAULT '';
DECLARE WK_NORCML			VARCHAR(100)	DEFAULT '';
DECLARE WK_TTINTC			VARCHAR(100)	DEFAULT '';
DECLARE WK_CPRVCL			VARCHAR(100)	DEFAULT '';
DECLARE WK_STATOC			VARCHAR(100)	DEFAULT '';
DECLARE WK_FORCML			VARCHAR(100)	DEFAULT '';
DECLARE WK_FMPDME			VARCHAR(100)	DEFAULT '';
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2;

IF IN_CCLNT <> 0 THEN
	SET WK_CCLNT = ' RZOL38.CCLNT = ' || IN_CCLNT || ' And ';
END IF;

IF IN_NORCML <> '' THEN
	SET WK_NORCML = ' AND RZOL38.NORCML = ''' || IN_NORCML || ''' ';
END IF;

IF IN_CPRVCL <> 0 THEN
	SET WK_CPRVCL = ' AND RZOL38.CPRVCL = ' || IN_CPRVCL ;
END IF;

IF IN_TTINTC <> '' THEN
	SET WK_TTINTC = ' AND RZOL38.TTINTC = ''' || IN_TTINTC || ''' ';
END IF;

IF IN_FORCMI > 0 AND IN_FORCMF > 0 THEN
	SET WK_FORCML = ' AND RZOL38.FORCML BETWEEN ' || IN_FORCMI || ' AND ' || IN_FORCMF;
ELSE
	IF IN_FORCMI > 0 THEN
		SET WK_FORCML = ' AND RZOL38.FORCML >= ' || IN_FORCMI;
	END IF;
	IF IN_FORCMF > 0 THEN
		SET WK_FORCML = ' AND RZOL38.FORCML <= ' || IN_FORCMF;
	END IF;
END IF;

IF IN_FMPDMI > 0 AND IN_FMPDMF > 0 THEN
	SET WK_FMPDME = ' AND RZOL39.FMPDME BETWEEN ' || IN_FMPDMI || ' AND ' || IN_FMPDMF;
ELSE
	IF IN_FMPDMI > 0 THEN
		SET WK_FMPDME = ' AND RZOL39.FMPDME >= ' || IN_FMPDMI;
	END IF;
	IF IN_FMPDMF > 0 THEN
		SET WK_FMPDME = ' AND RZOL39.FMPDME <= ' || IN_FMPDMF;
	END IF;
END IF;

IF IN_STATOC <> '' THEN
	IF IN_STATOC = 'A' THEN
		SET WK_STATOC = ' AND ( RZOL39.QCNTIT - RZOL39.QCNRCP ) <= 0 ';
	ELSE
		SET WK_STATOC = ' AND ( RZOL39.QCNTIT - RZOL39.QCNRCP ) > 0 ';
	END IF;
END IF;

-- Armamos la consulta final con toda la información
SET strSQL = '	SELECT  CCLNT, (SELECT TCMPCL FROM RZZM01 WHERE CCLNT = t1.CCLNT) TCMPCL, CPRVCL, (SELECT TPRVCL FROM RZOL05 WHERE CPRVCL = t1.CPRVCL ) TPRVCL, 
						NORCML, NRITOC, TDITES, QCNTIT, FORCML, FMPDME, FREFFW, 
						CASE WHEN IFNULL( FEACTU - FMPDME, 0 ) < 0 AND FREFFW IS NULL THEN 0
							 ELSE IFNULL( FEACTU - FMPDME, 0 )
						END NDIATR, 
						QBLTSR, ( QCNTIT - QBLTSR ) QCNPEN, STFREC,
						CASE WHEN IFNULL( FMPDME - FEACTU, 0) > 0 AND FREFFW IS NULL THEN ''EN EL PLAZO''
							 WHEN IFNULL( FMPDME - FEACTU, 0) > 0 AND NOT( FREFFW IS NULL) THEN ''ANTICIPADO''
							 WHEN IFNULL( FMPDME - FEACTU, 0) = 0 THEN ''EN EL PLAZO''
							 ELSE ''ATRASADO'' 
						END	STFENT
				FROM  ( SELECT	RZOL38.CCLNT, RZOL38.CPRVCL, RZOL38.NORCML, RZOL39.NRITOC, RZOL39.TDITES, RZOL39.QCNTIT, NumberToDate(RZOL38.FORCML) FORCML, 
								NumberToDate(RZOL39.FMPDME) FMPDME, IFNULL( RZOL66.QBLTSR, 0) QBLTSR, NumberToDate(RZOL65.FREFFW) FREFFW, 
								CASE WHEN RZOL65.FREFFW IS NULL THEN CURRENT DATE 
									 ELSE NumberToDate(RZOL65.FREFFW) 
								END FEACTU,
								CASE WHEN RZOL66.CREFFW IS NULL THEN ''PENDIENTE'' 
									 ELSE ( CASE WHEN RZOL39.QCNTIT <= RZOL39.QCNRCP THEN ''ATENDIDA'' ELSE ''PENDIENTE'' END) 
								END STFREC
						FROM    RZOL38 INNER JOIN RZOL39
						ON	' || WK_CCLNT || ' RZOL38.CCLNT  = RZOL39.CCLNT ' || WK_NORCML || WK_FORCML || WK_TTINTC || WK_CPRVCL || '
						AND		RZOL38.NORCML = RZOL39.NORCML
						AND		RZOL38.SESTRG <> ''*''
						AND		RZOL39.SESTRG <> ''*'' ' || WK_FMPDME || WK_STATOC || ' 
						LEFT OUTER JOIN RZOL66
						ON		RZOL66.CCLNT  = RZOL39.CCLNT
						AND		RZOL66.NORCML = RZOL39.NORCML
						AND		RZOL66.NRITOC = RZOL39.NRITOC
						AND		RZOL66.SESTRG <> ''*''
						LEFT OUTER JOIN RZOL65
						ON		RZOL65.CCLNT  = RZOL66.CCLNT
						AND		RZOL65.CREFFW = RZOL66.CREFFW
						AND		RZOL65.SESTRG <> ''*''
					  ) t1
				ORDER BY t1.CCLNT, t1.CPRVCL, t1.NORCML, t1.NRITOC ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S2 FROM strSQL;
OPEN CU_02;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L02 TO PUBLIC