-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L01(NUMERIC(6, 0), VARCHAR(35),NUMERIC(4),NUMERIC(3), NUMERIC(3))
GO

CREATE PROCEDURE  SP_SOLMIN_OC_ITEM_RZOL39_L01 (
        IN IN_CCLNT NUMERIC(6, 0) ,
        IN IN_NORCML VARCHAR(35) ,
        IN "PAGESIZE" NUMERIC(4, 0) ,
        IN PAGENUMBER NUMERIC(3, 0) ,
        OUT PAGECOUNT NUMERIC(3, 0) )
        DYNAMIC RESULT SETS 1
        LANGUAGE SQL
        BEGIN
DECLARE CR CURSOR FOR
                        SELECT *
                        FROM ( SELECT ROW_NUMBER ( ) OVER ( ) ROWNUMBER ,
                        R39.NRITOC ,
                        R39.TCITCL ,
                        R39.TCITPR ,
                        R39.TDITES ,
                        R39.TDITIN ,
                        R39.CPTDAR ,
                        R39.QCNTIT ,
                        R39.TUNDIT ,
                        R39.IVUNIT ,
                        R39.IVTOIT ,
                        R39.QTOLMAX ,
                        R39.QTOLMIN ,
                        R39.TCTCST ,
                        NUMBERTODATE ( R39.FMPDME ) AS FMPDME ,
                        NUMBERTODATE ( R39.FMPIME ) AS FMPIME ,
                        R39.TLUGOR ,
                        R39.TLUGEN ,
                        R39.TRFRN ,
                        R39.QCNTIT - R39 .QCNRCP QCNPEN ,
                        FN_SOLMIN_OC_SUBITEM_RZOL39S_CANTIDAD_SUBITEMS_X_ITEM ( R39.CCLNT , R39.NORCML , R39.NRITOC ) ESSUBITEM ,
                        IFNULL ( ( SELECT CMRCD FROM RZOL11 WHERE RZOL11 . CCLNT = R39. CCLNT AND TRIM ( RZOL11 . CMRCLR ) = TRIM ( R39. TCITCL ) ) , '' ) AS CMRCD ,
                        IFNULL ( ( SELECT TMRCD2 FROM RZOL11 WHERE RZOL11 . CCLNT = R39. CCLNT AND TRIM ( RZOL11 . CMRCLR ) = TRIM ( R39. TCITCL ) ) , '' ) AS TMRCD2 ,
                        IFNULL ( ( SELECT NORDSR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NORDSR ,
                        IFNULL ( ( SELECT NCNTR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NCNTR ,
                        IFNULL ( ( SELECT NCRCTC FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NCRCTC ,
                        IFNULL ( ( SELECT NAUTR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NAUTR ,
                        IFNULL ( ( SELECT FUNDS2 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS FUNDS2 ,
                        IFNULL ( ( SELECT CTPDP6 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CTPDPS ,
                        IFNULL ( ( SELECT CUNCN5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNCN5 ,
                        IFNULL ( ( SELECT CUNPS5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNPS5 ,
                        IFNULL ( ( SELECT CUNVL5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNVL5
                        FROM RZOL39 R39
                        WHERE R39.NORCML = IN_NORCML AND R39.CCLNT = IN_CCLNT AND R39.SESTRG <> '*' ) AS CON
                        WHERE ROWNUMBER BETWEEN ( PAGESIZE * ( PAGENUMBER - 1 ) + 1 ) AND ( PAGESIZE * ( ( PAGENUMBER - 1 ) + 1 ) ) ;



                        SELECT ( CASE WHEN ( COUNT ( 1 ) / PAGESIZE ) > INTEGER ( ( COUNT ( 1 ) / PAGESIZE ) )
                        THEN INTEGER ( COUNT ( 1 ) / PAGESIZE + 1 ) ELSE INTEGER ( COUNT ( 1 ) / PAGESIZE ) END ) INTO PAGECOUNT
                        FROM RZOL39
                        WHERE NORCML = IN_NORCML AND CCLNT = IN_CCLNT AND SESTRG <> '*' ;

-- Realizamos la preparación de la Consulta para ser ejecutada
OPEN CR ;
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L01(NUMERIC(6, 0), VARCHAR(35),NUMERIC(4),NUMERIC(3), NUMERIC(3)) TO PUBLIC
go
-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L01( VARCHAR(2), VARCHAR(1), NUMERIC(3),NUMERIC(6, 0), VARCHAR(35),NUMERIC(4),NUMERIC(3), NUMERIC(3))
GO

CREATE PROCEDURE  SP_SOLMIN_OC_ITEM_RZOL39_L01 (
        IN IN_CCMPN   VARCHAR(2) ,
        IN IN_CDVSN   VARCHAR(1) ,
        IN IN_CPLNDV  NUMERIC(3) ,
        IN IN_CCLNT   NUMERIC(6) ,
        IN IN_NORCML  VARCHAR(35) ,
        IN "PAGESIZE" NUMERIC(4, 0) ,
        IN PAGENUMBER NUMERIC(3, 0) ,
        OUT PAGECOUNT NUMERIC(3, 0) )
        DYNAMIC RESULT SETS 1
        LANGUAGE SQL
        BEGIN
DECLARE CR CURSOR FOR
                        SELECT *
                        FROM ( SELECT ROW_NUMBER ( ) OVER ( ) ROWNUMBER ,
                        R39.NRITOC ,
                        R39.TCITCL ,
                        R39.TCITPR ,
                        R39.TDITES ,
                        R39.TDITIN ,
                        R39.CPTDAR ,
                        R39.QCNTIT ,
                        R39.TUNDIT ,
                        R39.IVUNIT ,
                        R39.IVTOIT ,
                        R39.QTOLMAX ,
                        R39.QTOLMIN ,
                        R39.TCTCST ,
                        NUMBERTODATE ( R39.FMPDME ) AS FMPDME ,
                        NUMBERTODATE ( R39.FMPIME ) AS FMPIME ,
                        R39.TLUGOR ,
                        R39.TLUGEN ,
                        R39.TRFRN ,
                        ifnull(R39.QCNTIT - R39I.QCNRCP,R39.QCNTIT) QCNPEN ,
                        FN_SOLMIN_OC_SUBITEM_RZOL39S_CANTIDAD_SUBITEMS_X_ITEM ( R39.CCLNT , R39.NORCML , R39.NRITOC ) ESSUBITEM ,
                        IFNULL ( ( SELECT CMRCD FROM RZOL11 WHERE RZOL11 . CCLNT = R39. CCLNT AND TRIM ( RZOL11 . CMRCLR ) = TRIM ( R39. TCITCL ) ) , '' ) AS CMRCD ,
                        IFNULL ( ( SELECT TMRCD2 FROM RZOL11 WHERE RZOL11 . CCLNT = R39. CCLNT AND TRIM ( RZOL11 . CMRCLR ) = TRIM ( R39. TCITCL ) ) , '' ) AS TMRCD2 ,
                        IFNULL ( ( SELECT NORDSR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NORDSR ,
                        IFNULL ( ( SELECT NCNTR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NCNTR ,
                        IFNULL ( ( SELECT NCRCTC FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NCRCTC ,
                        IFNULL ( ( SELECT NAUTR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NAUTR ,
                        IFNULL ( ( SELECT FUNDS2 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS FUNDS2 ,
                        IFNULL ( ( SELECT CTPDP6 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CTPDPS ,
                        IFNULL ( ( SELECT CUNCN5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNCN5 ,
                        IFNULL ( ( SELECT CUNPS5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNPS5 ,
                        IFNULL ( ( SELECT CUNVL5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNVL5
                        FROM  RZOL39 R39 LEFT JOIN RZOL39I R39I ON   R39I.CCLNT=R39.CCLNT AND R39I.NORCML=R39.NORCML AND R39I.CCMPN= IN_CCMPN AND R39I.CDVSN=IN_CDVSN AND R39I.CPLNDV=IN_CPLNDV AND  R39I.NRITOC=R39.NRITOC
                        WHERE R39.NORCML = IN_NORCML AND R39.CCLNT = IN_CCLNT AND R39.SESTRG <> '*' ) AS CON
                        WHERE ROWNUMBER BETWEEN ( PAGESIZE * ( PAGENUMBER - 1 ) + 1 ) AND ( PAGESIZE * ( ( PAGENUMBER - 1 ) + 1 ) ) ;



                        SELECT ( CASE WHEN ( COUNT ( 1 ) / PAGESIZE ) > INTEGER ( ( COUNT ( 1 ) / PAGESIZE ) )
                        THEN INTEGER ( COUNT ( 1 ) / PAGESIZE + 1 ) ELSE INTEGER ( COUNT ( 1 ) / PAGESIZE ) END ) INTO PAGECOUNT
                        FROM RZOL39
                        WHERE NORCML = IN_NORCML AND CCLNT = IN_CCLNT AND SESTRG <> '*' ;

-- Realizamos la preparación de la Consulta para ser ejecutada
OPEN CR ;
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L01(VARCHAR(2), VARCHAR(1), NUMERIC(3),NUMERIC(6, 0), VARCHAR(35),NUMERIC(4),NUMERIC(3), NUMERIC(3)) TO PUBLIC
GO

DROP PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L01( VARCHAR(2), VARCHAR(1), NUMERIC(3),NUMERIC(6, 0), VARCHAR(35),VARCHAR(100),NUMERIC(4),NUMERIC(3), NUMERIC(3))
GO

CREATE PROCEDURE  SP_SOLMIN_OC_ITEM_RZOL39_L01 (
        IN IN_CCMPN   VARCHAR(2) ,
        IN IN_CDVSN   VARCHAR(1) ,
        IN IN_CPLNDV  NUMERIC(3) ,
        IN IN_CCLNT   NUMERIC(6) ,
        IN IN_NORCML  VARCHAR(35) ,
        IN IN_TDITES  VARCHAR(100),
        IN "PAGESIZE" NUMERIC(4, 0) ,
        IN PAGENUMBER NUMERIC(3, 0) ,
        OUT PAGECOUNT NUMERIC(3, 0) )
        DYNAMIC RESULT SETS 1
        LANGUAGE SQL
        BEGIN
DECLARE CR CURSOR FOR
                        SELECT *
                        FROM ( SELECT ROW_NUMBER ( ) OVER ( ) ROWNUMBER ,
                        R39.NRITOC ,
                        R39.TCITCL ,
                        R39.TCITPR ,
                        R39.TDITES ,
                        R39.TDITIN ,
                        R39.CPTDAR ,
                        R39.QCNTIT ,
                        R39.TUNDIT ,
                        R39.IVUNIT ,
                        R39.IVTOIT ,
                        R39.QTOLMAX ,
                        R39.QTOLMIN ,
                        R39.TCTCST ,
                        NUMBERTODATE ( R39.FMPDME ) AS FMPDME ,
                        NUMBERTODATE ( R39.FMPIME ) AS FMPIME ,
                        R39.TLUGOR ,
                        R39.TLUGEN ,
                        R39.TRFRN ,
                        ifnull(R39.QCNTIT - R39I.QCNRCP,R39.QCNTIT) QCNPEN ,
                        FN_SOLMIN_OC_SUBITEM_RZOL39S_CANTIDAD_SUBITEMS_X_ITEM ( R39.CCLNT , R39.NORCML , R39.NRITOC ) ESSUBITEM ,
                        IFNULL ( ( SELECT CMRCD FROM RZOL11 WHERE RZOL11 . CCLNT = R39. CCLNT AND TRIM ( RZOL11 . CMRCLR ) = TRIM ( R39. TCITCL ) ) , '' ) AS CMRCD ,
                        IFNULL ( ( SELECT TMRCD2 FROM RZOL11 WHERE RZOL11 . CCLNT = R39. CCLNT AND TRIM ( RZOL11 . CMRCLR ) = TRIM ( R39. TCITCL ) ) , '' ) AS TMRCD2 ,
                        IFNULL ( ( SELECT NORDSR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NORDSR ,
                        IFNULL ( ( SELECT NCNTR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NCNTR ,
                        IFNULL ( ( SELECT NCRCTC FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NCRCTC ,
                        IFNULL ( ( SELECT NAUTR FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , 0 ) AS NAUTR ,
                        IFNULL ( ( SELECT FUNDS2 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS FUNDS2 ,
                        IFNULL ( ( SELECT CTPDP6 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CTPDPS ,
                        IFNULL ( ( SELECT CUNCN5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNCN5 ,
                        IFNULL ( ( SELECT CUNPS5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNPS5 ,
                        IFNULL ( ( SELECT CUNVL5 FROM RZIT05 WHERE RZIT05 . CCLNT2 = R39. CCLNT AND TRIM ( RZIT05 . CMRCLR ) = TRIM ( R39. TCITCL ) FETCH FIRST ROWS ONLY ) , '' ) AS CUNVL5
                        FROM  RZOL39 R39 LEFT JOIN RZOL39I R39I ON   R39I.CCLNT=R39.CCLNT AND R39I.NORCML=R39.NORCML AND R39I.CCMPN= IN_CCMPN AND R39I.CDVSN=IN_CDVSN AND R39I.CPLNDV=IN_CPLNDV AND  R39I.NRITOC=R39.NRITOC
                        WHERE R39.NORCML = IN_NORCML  AND R39.CCLNT = IN_CCLNT AND R39.SESTRG <> '*' AND TDITES LIKE '%'||IN_TDITES|| '%') AS CON
                        WHERE ROWNUMBER BETWEEN ( PAGESIZE * ( PAGENUMBER - 1 ) + 1 ) AND ( PAGESIZE * ( ( PAGENUMBER - 1 ) + 1 ) ) ;



                        SELECT ( CASE WHEN ( COUNT ( 1 ) / PAGESIZE ) > INTEGER ( ( COUNT ( 1 ) / PAGESIZE ) )
                        THEN INTEGER ( COUNT ( 1 ) / PAGESIZE + 1 ) ELSE INTEGER ( COUNT ( 1 ) / PAGESIZE ) END ) INTO PAGECOUNT
                        FROM RZOL39
                        WHERE NORCML = IN_NORCML AND CCLNT = IN_CCLNT AND SESTRG <> '*' AND TDITES LIKE '%'||IN_TDITES|| '%' ;

-- Realizamos la preparación de la Consulta para ser ejecutada
OPEN CR ;
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_L01(VARCHAR(2), VARCHAR(1), NUMERIC(3),NUMERIC(6, 0), VARCHAR(35),VARCHAR(100),NUMERIC(4),NUMERIC(3), NUMERIC(3)) TO PUBLIC