-- CAMBIAR RNSLIB POR DESLIB

DROP PROCEDURE  SP_SOLMIN_OC_RZOL38_INS
GO
DROP PROCEDURE SP_SOLMIN_OC_RZOL38_INS
GO
CREATE PROCEDURE  SP_SOLMIN_OC_RZOL38_INS (
        IN IN_CCLNT NUMERIC(6, 0) ,
        IN IN_NORCML VARCHAR(35) ,
        IN IN_CPRVCL NUMERIC(6, 0) ,
        IN IN_FORCML NUMERIC(8, 0) ,
        IN IN_FSOLIC NUMERIC(8, 0) ,
        IN IN_TDSCML VARCHAR(50) ,
        IN IN_TCMAEM VARCHAR(30) ,
        IN IN_TTINTC VARCHAR(6) ,
        IN IN_NREFCL VARCHAR(15) ,
        IN IN_TPAGME VARCHAR(25) ,
        IN IN_REFDO1 VARCHAR(100) ,
        IN IN_NTPDES NUMERIC(2, 0) ,
        IN IN_CMNDA1 NUMERIC(3, 0) ,
        IN IN_TEMPFAC VARCHAR(50) ,
        IN IN_TNOMCOM VARCHAR(30) ,
        IN IN_TCTCST VARCHAR(6) ,
        IN IN_CREGEMB VARCHAR(2) ,
        IN IN_CMEDTR NUMERIC(2, 0) ,
        IN IN_TDEFIN VARCHAR(24) ,
        IN IN_IVCOTO NUMERIC(15, 5) ,
        IN IN_IVTOCO NUMERIC(15, 5) ,
        IN IN_IVTOIM NUMERIC(15, 5) ,
        IN IN_TDAITM VARCHAR(1000) ,
        IN IN_USUARI VARCHAR(10) )
        LANGUAGE SQL
        BEGIN ATOMIC
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- Variables de Trabajo - Seguridad  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
DECLARE WK_FECHA NUMERIC ( 10 , 0 ) DEFAULT 0 ;
DECLARE WK_HORA NUMERIC ( 10 , 0 ) DEFAULT 0 ;
-- -- -- -- -- -- -- -- -- -- -- -- --
-- Variables de Trabajo  --
-- -- -- -- -- -- -- -- -- -- -- -- --
DECLARE WK_TDAITM VARCHAR ( 1000 ) DEFAULT '' ;
DECLARE WK_OBSTEM VARCHAR ( 100 ) DEFAULT '' ;
DECLARE WK_NCRRLT NUMERIC ( 3 , 0 ) DEFAULT 0 ;
DECLARE WK_NMONOC VARCHAR ( 10 ) DEFAULT '' ;

-- Obtengo la fecha y hora actual
SET WK_FECHA = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ;
SET WK_HORA = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ;

SET WK_TDAITM = IN_TDAITM ;
-- Validamos el simbolo de moneda con la que se va a almacenar la información
SELECT TSGNMN
INTO WK_NMONOC
FROM RZZK02
WHERE CMNDA1 = IN_CMNDA1 ;

-- Generamos el Código del WayBill - Bulto
IF NOT EXISTS ( SELECT NORCML FROM RZOL38 WHERE CCLNT = IN_CCLNT AND NORCML = IN_NORCML ) THEN

INSERT INTO RZOL38 ( CCLNT , NORCML , CPRVCL , CPRPCL , FORCML , FROCMP , TDSCML , TCTCST , NSVP , TTINTC ,
NREFCL , TPAGME , TLUGEM , TDEFIN , IVCOTO , IVTOCO , IVTOIM , CMNDA1 , NMONOC , SFACTU ,
FFACTU , STRANS , REFDO1 , FSOLIC , TCMAEM , TEMPFAC , TNOMCOM , CREGEMB , TPAISEM , CMEDTR ,
NTPDES , FLGMAI , SFLGES , CUSCRT , FCHCRT , HRACRT , CULUSA , FULTAC , HULTAC , SESTRG ,
UPDATE_IDENT )
VALUES ( IN_CCLNT , IN_NORCML , IN_CPRVCL , '' , IN_FORCML , IN_FORCML , IN_TDSCML , IN_TCTCST , '' , IN_TTINTC ,
IN_NREFCL , IN_TPAGME , '' , IN_TDEFIN , IN_IVCOTO , IN_IVTOCO , IN_IVTOIM , IN_CMNDA1 , WK_NMONOC , '' ,
0 , '' , IN_REFDO1 , IN_FSOLIC , IN_TCMAEM , IN_TEMPFAC , IN_TNOMCOM , IN_CREGEMB , '' , IN_CMEDTR ,
IN_NTPDES , 0 , '' , IN_USUARI , WK_FECHA , WK_HORA , IN_USUARI , WK_FECHA , WK_HORA , 'A' ,
1 ) ;

ELSE
UPDATE RZOL38
SET
CULUSA = IN_USUARI,
FULTAC = WK_FECHA,
HULTAC = WK_HORA,
CPRVCL = IN_CPRVCL ,
FORCML = IN_FORCML ,
FROCMP = IN_FORCML ,
FSOLIC = IN_FSOLIC ,
TDSCML = IN_TDSCML ,
TCMAEM = IN_TCMAEM ,
TTINTC = IN_TTINTC ,
NREFCL = IN_NREFCL ,
TPAGME = IN_TPAGME ,
REFDO1 = IN_REFDO1 ,
NTPDES = IN_NTPDES ,
CMNDA1 = IN_CMNDA1 ,
NMONOC = WK_NMONOC ,
TEMPFAC = IN_TEMPFAC ,
TNOMCOM = IN_TNOMCOM ,
TCTCST = IN_TCTCST ,
CREGEMB = IN_CREGEMB ,
CMEDTR = IN_CMEDTR ,
TDEFIN = IN_TDEFIN ,
IVCOTO = IN_IVCOTO ,
IVTOCO = IN_IVTOCO ,
IVTOIM = IN_IVTOIM ,
SESTRG = 'A'
WHERE CCLNT = IN_CCLNT
AND NORCML = IN_NORCML ;
END IF ;

-- Eliminamos las observaciones que puedan estar registradas
DELETE FROM RZOL38B
WHERE CCLNT = IN_CCLNT
AND NORCML = IN_NORCML ;

WHILE LENGTH ( WK_TDAITM ) > 0 DO
IF LENGTH ( WK_TDAITM ) > 100 THEN
SET WK_OBSTEM = SUBSTR ( WK_TDAITM , 1 , 100 ) ;
SET WK_TDAITM = SUBSTR ( WK_TDAITM , 101 ) ;
ELSE
SET WK_OBSTEM = WK_TDAITM ;
SET WK_TDAITM = '' ;
END IF ;
SET WK_NCRRLT = WK_NCRRLT + 1 ;

INSERT INTO RZOL38B ( CCLNT , NORCML , NCRRLT , TNOTAS , CULUSA , FULTAC , HULTAC , UPDATE_IDENT )
VALUES ( IN_CCLNT , IN_NORCML , WK_NCRRLT , WK_OBSTEM , IN_USUARI , WK_FECHA , WK_HORA , 1 ) ;
END WHILE ;
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_RZOL38_INS TO PUBLIC
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_RZOL38_INS TO PUBLIC