drop procedure SP_SOLMIN_OC_ITEM_RZOL39_INS
GO
CREATE PROCEDURE  SP_SOLMIN_OC_ITEM_RZOL39_INS (
        IN IN_CCLNT NUMERIC(6, 0) ,
        IN IN_NORCML VARCHAR(35) ,
        IN IN_NRITOC NUMERIC(6, 0) ,
        IN IN_TCITCL VARCHAR(20) ,
        IN IN_TCITPR VARCHAR(20) ,
        IN IN_TDITES VARCHAR(100) ,
        IN IN_TDITIN VARCHAR(100) ,
        IN IN_CPTDAR VARCHAR(18) ,
        IN IN_QCNTIT NUMERIC(15, 5) ,
        IN IN_TUNDIT VARCHAR(10) ,
        IN IN_IVUNIT NUMERIC(15, 5) ,
        IN IN_IVTOIT NUMERIC(15, 5) ,
        IN IN_QTOLMIN NUMERIC(15, 5) ,
        IN IN_QTOLMAX NUMERIC(15, 5) ,
        IN IN_FMPDME NUMERIC(8, 0) ,
        IN IN_FMPIME NUMERIC(8, 0) ,
        IN IN_TLUGOR VARCHAR(50) ,
        IN IN_TLUGEN VARCHAR(50) ,
        IN IN_TCTCST VARCHAR(6) ,
        IN IN_TRFRN VARCHAR(50) ,
        IN IN_USUARI VARCHAR(10) )
        LANGUAGE SQL
        BEGIN ATOMIC
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
-- Variables de Trabajo - Seguridad   --
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
DECLARE WK_FECHA NUMERIC ( 10 , 0 ) DEFAULT 0 ;
DECLARE WK_HORA NUMERIC ( 10 , 0 ) DEFAULT 0 ;
DECLARE STRTRFRNA VARCHAR(50)      DEFAULT '';
--  --  --  --  --  --  --  --  --  --  --  --  --
-- Variables de Trabajo   --
--  --  --  --  --  --  --  --  --  --  --  --  --
DECLARE WK_IVTOIT NUMERIC ( 15 , 5 ) DEFAULT 0 ;

-- Obtengo la fecha y hora actual
SET WK_FECHA = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ;
SET WK_HORA = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ;

IF IN_IVTOIT = 0 THEN
SET WK_IVTOIT = IN_IVUNIT * IN_QCNTIT ;
ELSE
SET WK_IVTOIT = IN_IVTOIT ;
END IF ;

--SOLO PARA EL CLIENTE PLUSPETROL
        IF IN_CCLNT = 11731 OR IN_CCLNT=30507 THEN

                IF EXISTS(SELECT NLTECL  FROM RZOL05B WHERE CCLNT=IN_CCLNT AND NLTECL= SUBSTRING(IN_TLUGEN,0,8) ) THEN
                  SET STRTRFRNA  =  SUBSTRING(IN_TLUGEN,0,8);
                  SET IN_TLUGEN  =  SUBSTRING(IN_TLUGEN,8,42);
                END IF;
        END IF;
-- Generamos el Código del WayBill - Bulto
IF NOT EXISTS ( SELECT NRITOC FROM RZOL39 WHERE CCLNT = IN_CCLNT AND NORCML = IN_NORCML AND NRITOC = IN_NRITOC ) THEN
-- Obtenemos el último nro. del Item + 1
IF IN_NRITOC = 0 THEN
SELECT IFNULL ( MAX ( NRITOC ) , 0 ) + 1
INTO IN_NRITOC
FROM RZOL39
WHERE CCLNT = IN_CCLNT
AND NORCML = IN_NORCML ;
END IF ;

INSERT INTO RZOL39 ( CCLNT , NORCML , NRITOC , TCITCL , TCITPR , TDITES , TDITIN , CPTDAR , QCNTIT ,
QCNPEM , QCNEMB , QSDOIT , QINEMP , TUNDIT , IVUNIT , IVTOIT , FMPDME , FMPIME ,
TLUGEN ,TRFRNA, TCTCST , TRFRN , TLUGOR , FLGPEN , QCNRCP , QCNDPC , SFLGES , QSTKIT , QTOLMIN , QTOLMAX ,
QCNVRS , TUNDCN , SESEND , CUSCRT , FCHCRT , HRACRT , CULUSA , FULTAC , HULTAC ,
SESTRG , UPDATE_IDENT )
VALUES ( IN_CCLNT , IN_NORCML , IN_NRITOC , IN_TCITCL , IN_TCITPR , IN_TDITES , IN_TDITIN , IN_CPTDAR , IN_QCNTIT ,
0 , 0 , 0 , 0 , IN_TUNDIT , IN_IVUNIT , WK_IVTOIT , IN_FMPDME , IN_FMPIME ,
IN_TLUGEN ,STRTRFRNA, IN_TCTCST , IN_TRFRN , IN_TLUGOR , '' , 0 , 0 , '' , 0 , IN_QTOLMIN , IN_QTOLMAX ,
0 , '' , '' , IN_USUARI , WK_FECHA , WK_HORA , IN_USUARI , WK_FECHA , WK_HORA ,
'A' , 1 ) ;

UPDATE RZOL38
SET IVCOTO = IVCOTO + WK_IVTOIT
WHERE CCLNT = IN_CCLNT
AND NORCML = IN_NORCML ;
ELSE
UPDATE RZOL39
SET TCITCL = IN_TCITCL ,
TCITPR = IN_TCITPR ,
TDITES = IN_TDITES ,
TDITIN = IN_TDITIN ,
CPTDAR = IN_CPTDAR ,
QCNTIT = IN_QCNTIT ,
TUNDIT = IN_TUNDIT ,
IVUNIT = IN_IVUNIT ,
IVTOIT = IN_IVTOIT ,
QTOLMIN = IN_QTOLMIN ,
QTOLMAX = IN_QTOLMAX ,
FMPDME = IN_FMPDME ,
FMPIME = IN_FMPIME ,
TLUGOR = IN_TLUGOR ,
TLUGEN = IN_TLUGEN ,
TRFRNA =STRTRFRNA,
TCTCST = IN_TCTCST ,
TRFRN = IN_TRFRN ,
CULUSA = IN_USUARI ,
FULTAC = WK_FECHA ,
HULTAC = WK_HORA ,
SESTRG = 'A'
WHERE CCLNT = IN_CCLNT
AND NORCML = IN_NORCML
AND NRITOC = IN_NRITOC ;


UPDATE RZOL38
SET IVCOTO = IFNULL ( ( SELECT SUM ( IVTOIT ) FROM RZOL39 WHERE CCLNT = IN_CCLNT AND NORCML = IN_NORCML AND SESTRG <> '*' ) , 0 )
WHERE CCLNT = IN_CCLNT
AND NORCML = IN_NORCML ;
END IF ;
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_INS TO PUBLIC