-- CAMBIAR RNSLIB POR RNSLIB
DROP PROCEDURE SP_SOLMIN_OC_SUB_ITEM_RZOL39S_INS
GO
CREATE PROCEDURE SP_SOLMIN_OC_SUB_ITEM_RZOL39S_INS(
		IN IN_CCLNT			NUMERIC(6, 0),
		IN IN_NORCML		VARCHAR(35),
		IN IN_NRITOC		NUMERIC(6, 0),
		IN IN_SBITOC		VARCHAR(10),
		IN IN_TCITCL		VARCHAR(20),
		IN IN_TCITPR		VARCHAR(20),
		IN IN_TDITES		VARCHAR(100),
		IN IN_CPTDAR		VARCHAR(18),
		IN IN_CODTPN		VARCHAR(10),
		IN IN_QCNTIT		NUMERIC(15, 5),
		IN IN_TUNDIT		VARCHAR(10),
		IN IN_IVUNIT		NUMERIC(15, 5),
		IN IN_IVTOIT		NUMERIC(15, 5),
		-- Variables relacionadas a la seguridad
        IN IN_USUARI  		VARCHAR(10)
        )
RESULT SETS 0
LANGUAGE SQL
BEGIN ATOMIC
--------------------------------------
-- Variables de Trabajo - Seguridad --
--------------------------------------
DECLARE	WK_FECHA	NUMERIC(10, 0)	DEFAULT 0;
DECLARE	WK_HORA		NUMERIC(10, 0)	DEFAULT 0;
--------------------------
-- Variables de Trabajo --
--------------------------
DECLARE WK_IVTOIT	NUMERIC(15, 5)	DEFAULT 0;

-- Obtengo la fecha y hora actual
SET	WK_FECHA = YEAR(CURRENT DATE) * 10000 + MONTH(CURRENT DATE) * 100 + DAY(CURRENT DATE);
SET	WK_HORA  = HOUR(CURRENT TIME) * 10000 + MINUTE(CURRENT TIME) * 100 + SECOND(CURRENT TIME);

IF IN_IVTOIT = 0 THEN
	SET WK_IVTOIT = IN_IVUNIT * IN_QCNTIT;
ELSE
	SET WK_IVTOIT = IN_IVTOIT;
END IF;

-- Generamos el Código del SubItem
IF NOT EXISTS(	SELECT SBITOC FROM RZOL39S WHERE CCLNT = IN_CCLNT AND NORCML = IN_NORCML AND NRITOC = IN_NRITOC AND SBITOC=IN_SBITOC ) THEN
	-- Obtenemos el último nro. del Item + 1

	INSERT INTO RZOL39S(CCLNT,		NORCML,		NRITOC,		SBITOC,     TCITCL,		TCITPR,		TDITES,		CPTDAR,		CODTPN,
	                    QCNTIT,		QCNPEM,		QCNEMB,		QSDOIT,		TUNDIT,		IVUNIT,		IVTOIT,		QCNRCP,		QCNDPC,		
	                    SFLGES,		QSTKIT,		CUSCRT,		FCHCRT,		HRACRT,		CULUSA,		FULTAC,		HULTAC,		SESTRG,		
	                    UPDATE_IDENT )
				VALUES(	IN_CCLNT,	IN_NORCML,	IN_NRITOC,	IN_SBITOC,	IN_TCITCL,	IN_TCITPR,	IN_TDITES,	IN_CPTDAR,	IN_CODTPN,
						IN_QCNTIT,	0,			0,			0,			IN_TUNDIT,	IN_IVUNIT,	WK_IVTOIT,	0,			0,			
						'',			0,			IN_USUARI,	WK_FECHA,	WK_HORA,	IN_USUARI,	WK_FECHA,	WK_HORA,	'A',		
						1 );
	
ELSE
	UPDATE	RZOL39S
	SET		TCITCL = IN_TCITCL,
			TCITPR = IN_TCITPR,
			TDITES = IN_TDITES,
			CPTDAR = IN_CPTDAR,
			CODTPN = IN_CODTPN,
			QCNTIT = IN_QCNTIT,
			TUNDIT = IN_TUNDIT,
			IVUNIT = IN_IVUNIT,
			IVTOIT = IN_IVTOIT,
			CULUSA = IN_USUARI,
			FULTAC = WK_FECHA,
			HULTAC = WK_HORA,
			SESTRG = 'A'
	WHERE	CCLNT  = IN_CCLNT
	AND		NORCML = IN_NORCML
	AND		NRITOC = IN_NRITOC
	AND     SBITOC = IN_SBITOC;
	
END IF;

END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39S_INS TO PUBLIC 