-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE SP_SOLMIN_OC_SUB_ITEM_RZOL39S_OBJ
GO
CREATE PROCEDURE SP_SOLMIN_OC_SUB_ITEM_RZOL39S_OBJ(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NORCML		VARCHAR(20),
		IN	IN_NRITOC		NUMERIC(6, 0),
		IN	IN_SBITOC		VARCHAR(10)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN ATOMIC
DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2;


-- Armamos la consulta final con toda la información
SET strSQL = '	SELECT	NRITOC, SBITOC, TCITCL, TCITPR, TDITES, CPTDAR, CODTPN, QCNTIT, TUNDIT, IVUNIT, IVTOIT
				FROM	RZOL39S
				WHERE	NORCML = ? And CCLNT = ? AND NRITOC = ? AND SBITOC = ?';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S2 FROM strSQL;
OPEN CU_02 USING IN_NORCML, IN_CCLNT, IN_NRITOC, IN_SBITOC;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_SUB_ITEM_RZOL39S_OBJ TO PUBLIC 