-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_OC_RZOL38_OBJ
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_OC_RZOL38_OBJ(
		IN	IN_CCLNT		NUMERIC(6, 0),
		IN	IN_NORCML		VARCHAR(35),
		OUT	OU_TDAITM		VARCHAR(1000)
        )
RESULT SETS 1
LANGUAGE SQL
BEGIN 
DECLARE strSQL  			VARCHAR(6000)	DEFAULT '';
DECLARE WK_TDAITM			VARCHAR(1000)	DEFAULT '';
DECLARE CU_00 SCROLL CURSOR WITH RETURN FOR S0;

FOR_LOOP:
FOR FILA AS CU_01 CURSOR FOR
SELECT  TNOTAS
FROM    RZOL38B
WHERE   CCLNT  = IN_CCLNT
And 	NORCML = IN_NORCML
ORDER BY NCRRLT
DO
	SET WK_TDAITM = WK_TDAITM || FILA.TNOTAS;
END FOR;

-- Armamos la consulta final con toda la información
SET strSQL = '	SELECT	NumberToDate(FORCML) as FORCML, NumberToDate(FSOLIC) as FSOLIC, TDSCML, TCMAEM, TTINTC, CPRVCL, CMNDA1, 
						TEMPFAC, TNOMCOM, TCTCST, CREGEMB, CMEDTR, TDEFIN, NREFCL, TPAGME, REFDO1, NTPDES, IVCOTO, IVTOCO, IVTOIM
				FROM	RZOL38
				WHERE	NORCML = ? AND CCLNT = ? ';
-- Realizamos la preparación de la Consulta para ser ejecutada
PREPARE S0 FROM strSQL;
OPEN CU_00 USING IN_NORCML, IN_CCLNT;

SET OU_TDAITM = WK_TDAITM;

END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_RZOL38_OBJ TO PUBLIC