-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_OC_ITEM_RZOL39_OBJ
GO

CREATE PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_OBJ ( 
	IN IN_CCLNT NUMERIC(6, 0) , 
	IN IN_NORCML VARCHAR(20) , 
	IN IN_NRITOC NUMERIC(6, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	BEGIN ATOMIC 
DECLARE STRSQL			VARCHAR ( 6000 )	DEFAULT '' ; 
DECLARE CU_02 SCROLL CURSOR WITH RETURN FOR S2 ; 
  
  
-- Armamos la consulta final con toda la información 
SET STRSQL = '	SELECT	NRITOC, TCITCL, TCITPR, TDITES, TDITIN, CPTDAR, QCNTIT, TUNDIT, IVUNIT, IVTOIT, QTOLMAX, QTOLMIN,
						NumberToDate(FMPDME) as FMPDME, NumberToDate(FMPIME) as FMPIME, TLUGOR, TLUGEN,TRFRN  
				FROM	RZOL39
				WHERE	NORCML = ? And CCLNT = ? AND NRITOC = ? ' ; 
-- Realizamos la preparación de la Consulta para ser ejecutada 
PREPARE S2 FROM STRSQL ; 
OPEN CU_02 USING IN_NORCML , IN_CCLNT , IN_NRITOC ; 
END

GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_OC_ITEM_RZOL39_OBJ TO PUBLIC