-- CAMBIAR RNSLIB POR DESLIB
DROP PROCEDURE DC@DESLIB.SP_SOLMIN_ACCESO
GO
CREATE PROCEDURE DC@DESLIB.SP_SOLMIN_ACCESO(
		IN 	IN_MMCAPL		VARCHAR(2),
		IN 	IN_MMCUSR		VARCHAR(10)
)
RESULT SETS 1
LANGUAGE SQL
BEGIN
DECLARE strSQL  VARCHAR(1000) DEFAULT '';
DECLARE CU_01 SCROLL CURSOR WITH RETURN FOR S1;

SET strSQL ='	SELECT  OPC_X_SIST.MMCAPL, OPC_X_SIST.MMCMNU, DIGITS(OPC_X_SIST.MMCOPC) MMCOPC,
						OPC_X_SIST.MMCAPL || OPC_X_SIST.MMCMNU || DIGITS( OPC_X_SIST.MMCOPC) AS MMNPVB,
						OPC_X_SIST.MMCAIN, OPC_X_SIST.MMCMIN, 
						OPC_X_SIST.MMCAIN || OPC_X_SIST.MMCMIN AS MMNQVB, 
						OPC_X_USER.MMCUSR
				FROM    MMOPCN OPC_X_SIST LEFT OUTER JOIN MMOPUS  OPC_X_USER
						ON      OPC_X_USER.MMCUSR = ''' || IN_MMCUSR || ''' 
						AND     OPC_X_SIST.MMCAPL = OPC_X_USER.MMCAPL
						AND     OPC_X_SIST.MMCMNU = OPC_X_USER.MMCMNU
						AND     OPC_X_SIST.MMCOPC = OPC_X_USER.MMCOPC
				WHERE   OPC_X_SIST.MMCAPL = ''' || IN_MMCAPL || '''';

PREPARE S1 FROM strSQL;
OPEN CU_01;
END
GO
GRANT ALL PRIVILEGES ON PROCEDURE SP_SOLMIN_ACCESO TO PUBLIC